stlx-1752 add tokens
BitGo/BitGoJS pull request #1033
Opened 2021-02-23 17:56 UTC by JulioAchaval-SimTLiX

2021-02-23 18:51 UTC, FabianSimtlix reviewed
LGTM

2021-02-24 18:54 UTC, barathcj commented
Please remove REN and Mana from the list as they failed internal audit. This needs to be removed from all components (indexer, microservices) as well

2021-02-24 18:55 UTC, barathcj requested changes
Remove REN and MANA

2021-02-24 19:47 UTC, barathcj approved these changes

2021-02-24 19:48 UTC, merged