feat(modules/bls-dkg): add BLS-DKG module needed for SDK key generation and HSM testing
BitGo/BitGoJS pull request #1034
Opened 2021-02-23 20:41 UTC by johnoliverdriscoll

BG-26226

2021-02-24 21:22 UTC, tylerlevine requested changes
Looks pretty good, just a few nits. I think the only change that's really required is putting the package under the `@bitgo` scope.

Some other things:
1) May want to consider using typescript - we are trying to move all the SDK code in that direction
2) Please verify that tests are running in CI as expected

2021-02-24 21:22 UTC, tylerlevine commented on modules/bls-dkg/package.json
> +  "name": "bls-dkg",
```suggestion
  "name": "@bitgo/bls-dkg",
```

2021-02-24 23:14 UTC, johnoliverdriscoll commented on modules/bls-dkg/index.js
> +function stringToBuffer(string) {
I wanted to to be easily used in a browser environment and I thought Buffer wasn't available.

2021-02-24 23:15 UTC, johnoliverdriscoll commented on modules/bls-dkg/index.js
> +
Yes, if Buffer is not available, this will do the same thing.

2021-02-24 23:16 UTC, johnoliverdriscoll commented on modules/bls-dkg/index.js
> +}
I know, but this is written in such a way that it is compatible with Uint8Array instead of Buffer.

2021-02-24 23:21 UTC, johnoliverdriscoll commented
Thanks for the review @tylerlevine . I have replied to your comments regarding Buffer and have updated the package name with an `@bitgo` prefix.

2021-02-24 23:55 UTC, johnoliverdriscoll commented
I've added a "unit-test" script key to bls-dkg's package.json and confirm that the tests are being run.

2021-02-26 19:57 UTC, tylerlevine approved these changes
Looks fine to me, however the build is not passing due to commit messages not following the conventional commits standard.

I know it's a bit of a pain, but we do this to make automatic release notes generation possible (although that's not finished yet). Would you mind rewriting your commits to follow the standard? Here's a link to the full spec: https://www.conventionalcommits.org/en/v1.0.0/

2021-02-26 23:10 UTC, johnoliverdriscoll commented
I was relying on the commit hook to help me format correctly and for some reason it didn't enforce the format for the last few commits I made. I've squashed them into one commit and I think the commit message is in the proper format.

2021-02-26 23:30 UTC, tylerlevine commented
> I was relying on the commit hook to help me format correctly and for some reason it didn't enforce the format for the last few commits I made. I've squashed them into one commit and I think the commit message is in the proper format.

strange, I'll have to look into that. Thanks for squashing

2021-02-26 23:30 UTC, tylerlevine approved these changes

2021-02-27 00:29 UTC, merged