feat(account-lib): add verifySignature Method
BitGo/BitGoJS pull request #1078
Opened 2021-03-22 18:03 UTC by JulioAchaval-SimTLiX

add method to verify msg and tx signatures

2021-03-22 18:31 UTC, rliberal-simtlix approved these changes
LGTM

2021-03-23 00:18 UTC, tylerlevine requested changes
I don't see a ticket for this in the PR or commit message - could you please add one?

Also, CSPR is using secp-based signatures right? Those don't have a fixed length (assuming they are DER encoded), so I'm not sure the length assertion is correct.

2021-03-23 19:26 UTC, CapnMigraine approved these changes
nice work!

2021-03-24 23:22 UTC, tylerlevine approved these changes

2021-03-24 23:23 UTC, merged