feat(statics): add requires reserve
BitGo/BitGoJS pull request #1107
Opened 2021-04-06 19:23 UTC by JulioAchaval-SimTLiX

add new param "requiesReserve" to all coins (only true for Casper)

[STLX-2337](https://bitgoinc.atlassian.net/browse/STLX-2337)

2021-04-06 22:13 UTC, tylerlevine requested changes
This is probably more appropriate as a `CoinFeature`: https://github.com/BitGo/BitGoJS/blob/ba2d8707fff934fe5124163bd78e52bf9a1730da/modules/statics/src/base.ts#L53

2021-04-07 14:45 UTC, tylerlevine approved these changes

2021-04-07 15:05 UTC, CapnMigraine submitted a review, later dismissed
LGTM with a nit comment

2021-04-07 15:05 UTC, CapnMigraine commented on modules/statics/src/base.ts
> +   * This coin requires a reserve amount to fund a wallet
nit: The reserve is not just for funding
```suggestion
   * This coin requires that accounts keep a minimum balance as reserve
```

2021-04-07 17:17 UTC, tylerlevine approved these changes

2021-04-07 17:22 UTC, CapnMigraine approved these changes

2021-04-08 12:48 UTC, merged