feat(cspr): update CSPR explorer URLs
BitGo/BitGoJS pull request #1162
Opened 2021-05-11 13:42 UTC by Krin2

Changing on account and explorer URLs for CSPR

STLX-1657

https://bitgoinc.atlassian.net/browse/STLX-1657

2021-05-11 14:50 UTC, smaria95 commented on modules/statics/src/networks.ts
> +
Remove this extra lines

2021-05-11 14:51 UTC, smaria95 commented on modules/statics/src/networks.ts
> +  explorerUrl = 'https://testnet.cspr.live/deploy/ ';
Please remove the extra space at the end of this string.

2021-05-11 16:59 UTC, JulioAchaval-SimTLiX submitted a review, later dismissed
LGTM

2021-05-11 17:19 UTC, JulioAchaval-SimTLiX submitted a review, later dismissed
LGTM

2021-05-11 19:52 UTC, CapnMigraine approved these changes
looks good

2021-05-11 20:07 UTC, rliberal-simtlix submitted a review, later dismissed

2021-05-13 18:38 UTC, tylerlevine requested changes
drone is failing, I think you need to rebase

2021-05-13 19:19 UTC, rliberal-simtlix approved these changes

2021-05-13 21:14 UTC, CapnMigraine approved these changes

2021-05-13 22:49 UTC, rliberal-simtlix approved these changes

2021-05-14 15:51 UTC, tylerlevine approved these changes

2021-05-14 16:16 UTC, JulioAchaval-SimTLiX approved these changes

2021-05-17 12:39 UTC, smaria95 approved these changes
LGTM

2021-05-17 16:13 UTC, merged