feat(core): export tx Enum Type from core
BitGo/BitGoJS pull request #1192
Opened 2021-05-27 14:23 UTC by alebusse

Added a Types class
Added getTransactionTypes() method to export the tx Enum Types imported from acccountLib
Added Unit test

[stlx-3452](https://bitgoinc.atlassian.net/browse/STLX-3452)

2021-05-27 14:45 UTC, rliberal-simtlix approved these changes

2021-05-27 15:58 UTC, CapnMigraine submitted a review, later dismissed
lgtm, but I'd like to have @tylerlevine's review as well.

2021-05-27 20:02 UTC, tylerlevine requested changes
Why do we need to re-export account lib types?

2021-05-27 20:23 UTC, rliberal-simtlix commented on modules/core/src/v2/types.ts
> +export class Types {
Talked with Tyler, better if we move this to basecoin
https://github.com/BitGo/BitGoJS/blob/db79e9500298563586a1febe1820ed245dda8fd7/modules/core/src/v2/baseCoin.ts#L4

2021-05-27 20:37 UTC, tylerlevine commented
Yeah, probably this is all we need to do in `core`:
```
diff --git a/modules/core/src/v2/baseCoin.ts b/modules/core/src/v2/baseCoin.ts
index 2a25d9f4..e58855a2 100644
--- a/modules/core/src/v2/baseCoin.ts
+++ b/modules/core/src/v2/baseCoin.ts
@@ -12,6 +12,10 @@ import { NodeCallback } from './types';
 import { RequestTracer } from './internal/util';
 const co = Bluebird.coroutine;
 
+// re-export account lib transaction types
+import { BaseCoin as AccountLibBasecoin } from '@bitgo/account-lib';
+export type TransactionType = AccountLibBasecoin.TransactionType;
+
 import { Wallet } from './wallet';
 import { Wallets } from './wallets';
 import { Markets } from './markets';
```

Then we can use it in the client by doing this:
```
import { BaseCoin } from 'bitgo';
// use BaseCoin.TransactionType
```

2021-05-27 22:20 UTC, tylerlevine approved these changes

2021-05-27 22:28 UTC, rliberal-simtlix approved these changes

2021-05-28 05:17 UTC, CapnMigraine approved these changes

2021-05-28 05:17 UTC, merged