feat(accountlib): add closeremaindeto and unit tests
BitGo/BitGoJS pull request #1301
Opened 2021-07-22 17:29 UTC by JulioAchaval-SimTLiX

increase coverage and provide disable tokens funcionality

[STLX-3878](https://bitgoinc.atlassian.net/browse/STLX-3878)

2021-07-22 17:38 UTC, rliberal-simtlix requested changes

2021-07-22 17:38 UTC, rliberal-simtlix commented on modules/account-lib/test/unit/coin/algo/transactionBuilder/assetTransferBuilder.ts
> +    it('should build a valid disable token transaction', async function() {
We need to include some failure cases @JulioAchaval-SimTLiX ?

2021-07-22 17:38 UTC, rliberal-simtlix commented on modules/account-lib/test/unit/coin/algo/transactionBuilder/assetTransferBuilder.ts
> +    it('should build a valid disable token transaction', async function() {
Other tests looks good

2021-07-23 15:32 UTC, rliberal-simtlix approved these changes

2021-07-23 16:22 UTC, pancham88 approved these changes

2021-07-23 16:22 UTC, merged