fix(core):[STLX-4989] fix getExtraPrebuildParams
BitGo/BitGoJS pull request #1328
Opened 2021-07-30 18:30 UTC by matilareo

fix getExtraPrebuildParams for TRX coin, contractCalls weren't building correctly

stlx-4989

2021-07-30 18:47 UTC, fmlenarduzzi approved these changes
LGTM

2021-08-02 13:21 UTC, mcasares-simtlix approved these changes

2021-08-03 15:42 UTC, twtaylorbitgo requested changes

2021-08-03 15:42 UTC, twtaylorbitgo commented on modules/core/src/v2/coins/trx.ts
> +    const recipients: any[] = [{ ...buildParams.recipients[0] }];
we need to check if this exists before we use a spread operator on it and that it can even be spread

2021-08-03 18:23 UTC, fmlenarduzzi approved these changes

2021-08-03 18:24 UTC, mcasares-simtlix approved these changes

2021-08-03 18:51 UTC, twtaylorbitgo approved these changes

2021-08-03 18:51 UTC, merged