fix(eth): goerli coins now set to gteth in core/src/config.ts
BitGo/BitGoJS pull request #1351
Opened 2021-08-04 23:13 UTC by bjon-bitgo

Before, we assumed erc20 tokens are either mainnet or kovan (If it is not eth, then it is teth).
erc20 tokens now can be eth, teth, and gteth

Ticket: BG-34419

2021-08-06 04:57 UTC, tylerlevine requested changes
test please

2021-08-10 17:08 UTC, wesgraham submitted a review, later dismissed

2021-08-10 17:13 UTC, tylerlevine submitted a review, later dismissed

2021-08-10 17:35 UTC, tylerlevine approved these changes

2021-08-10 17:35 UTC, merged