feat(account-lib): avalanche C implement transactionBuilder, transferBuilder, tests
BitGo/BitGoJS pull request #1395
Opened 2021-08-11 16:07 UTC by shiksb

TICKET: STLX-5079

2021-08-11 19:19 UTC, CapnMigraine reviewed
Please rebase to fix the merge conflicts

2021-08-11 20:03 UTC, smaria95 requested changes

2021-08-11 22:00 UTC, karankurbur commented on modules/account-lib/src/coin/avaxc/walletUtil.ts
> +export const flushCoinsMethodId = '';
Account lib is only used for ETH-like coins and not for ETH. ETH-like only support v2 so the method ids should match the v2 interface

2021-08-12 12:46 UTC, smaria95 commented on modules/account-lib/src/coin/avaxc/walletUtil.ts
> +export const flushCoinsMethodId = '';
@karankurbur, @CapnMigraine 
I did some extra research on this and I found that `uint` is actually an alias for `uint256`, for that reason the current `methodId` is working for the v2 contracts. 

https://docs.soliditylang.org/en/v0.5.3/types.html#integers


Also, I tested this PR changes with a script on sandbox. 
I managed to initialize a wallet and also send a transfer using accountLib to create the transaction and sending it with RPC Method `eth_sendRawTransaction` (which is the one used by indexer to broadcast eth-like transactions).

2021-08-12 13:10 UTC, smaria95 submitted a review, later dismissed
LGTM. 
Please remember to rebase and squash your branch.
Once you do that, you can ask for my re-review and I'll approve it again

2021-08-12 14:47 UTC, CapnMigraine approved these changes

2021-08-12 14:47 UTC, CapnMigraine commented on modules/account-lib/src/coin/avaxc/resources.ts
> + * TODO BG-35011: create custom Common object since Avalanche doesn't have hardforks
Moved to the STLX project (https://bitgoinc.atlassian.net/browse/STLX-5737)

2021-08-12 14:47 UTC, CapnMigraine commented on modules/account-lib/src/coin/avaxc/walletUtil.ts
> +// TODO BG-35012: determine if and how to use methodIds
Moved to the STLX project (https://bitgoinc.atlassian.net/browse/STLX-5738)

2021-08-12 18:22 UTC, smaria95 approved these changes
LGTM

2021-08-13 17:21 UTC, CapnMigraine approved these changes

2021-08-13 17:21 UTC, merged