feat: add ERC20 OFC "token" support to statics
BitGo/BitGoJS pull request #1401
Opened 2021-08-12 18:46 UTC by stevenharrisBG

Add ERC20 token support for ten new "tokens":
AAVE, BAT, COMP, GRT, LINK, MKR, SNX, UNI, USDT, and YFI.

2021-08-13 18:06 UTC, tylerlevine requested changes

2021-08-13 18:06 UTC, tylerlevine commented on modules/statics/src/coins.ts
> +  ofcerc20('aave', 'Aave', 18, UnderlyingAsset.AAVE),
The coin tickers need to be globally unique so that's causing the tests to fail. Can we continue using the `ofc` prefix on these?

2021-08-13 20:32 UTC, stevenharrisBG commented
I will post a new PR, this is an error.

On Fri, Aug 13, 2021 at 11:06 AM Tyler Levine ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In modules/statics/src/coins.ts
> <https://github.com/BitGo/BitGoJS/pull/1401#discussion_r688693574>:
>
> >    ofcerc20('ofcusdc', 'USD Coin', 6, UnderlyingAsset.USDC),
> +  ofcerc20('aave', 'Aave', 18, UnderlyingAsset.AAVE),
>
> The coin tickers need to be globally unique so that's causing the tests to
> fail. Can we continue using the ofc prefix on these?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/BitGo/BitGoJS/pull/1401#pullrequestreview-729858366>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALBOZQL3QOOEPMY2HF6OOL3T4VNMHANCNFSM5CB4TOYQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-14 03:30 UTC, tylerlevine approved these changes

2021-08-14 03:30 UTC, merged