fix(core): Add algo seed encoding
BitGo/BitGoJS pull request #1487
Opened 2021-09-03 04:53 UTC by CapnMigraine

Add logic to convert a stellar seed to algo encoding

CLOSES TICKET: STLX-6599

2021-09-03 12:44 UTC, rliberal-simtlix reviewed
Changes looks good just nits

2021-09-03 12:44 UTC, rliberal-simtlix commented on modules/account-lib/src/coin/algo/seedEncoding.ts
> +   * @param seed
Nit: add method title or comment

2021-09-03 12:44 UTC, rliberal-simtlix commented on modules/core/src/v2/coins/algo.ts
> +  isStellarSeed(seed: string): boolean {
Add js doc

2021-09-03 12:44 UTC, rliberal-simtlix commented on modules/core/src/v2/coins/algo.ts
> +  convertFromStellarSeed(seed: string): string | null {
Add js doc

2021-09-03 12:59 UTC, CapnMigraine commented on modules/account-lib/src/coin/algo/seedEncoding.ts
> +   * @param seed
done

2021-09-03 12:59 UTC, CapnMigraine commented on modules/core/src/v2/coins/algo.ts
> +  isStellarSeed(seed: string): boolean {
done

2021-09-03 12:59 UTC, CapnMigraine commented on modules/core/src/v2/coins/algo.ts
> +  convertFromStellarSeed(seed: string): string | null {
done

2021-09-03 13:01 UTC, rliberal-simtlix approved these changes

2021-09-03 13:04 UTC, JulioAchaval-SimTLiX approved these changes

2021-09-03 15:04 UTC, smaria95 approved these changes
LGTM

2021-09-03 16:01 UTC, Krin2 approved these changes

2021-09-17 06:30 UTC, tylerlevine requested changes

2021-09-17 06:30 UTC, tylerlevine commented on modules/account-lib/src/coin/algo/seedEncoding.ts
> +const MALFORMED_SEED_ERROR = new Error('seed seems to be malformed');
nit: create the error where it gets thrown, otherwise the stack trace won't be very helpful.

2021-09-17 06:31 UTC, tylerlevine requested changes
please rebase due to breaking changes in underlying utxolib library. I don't think this PR should be affected by this but I think it would be good to rebase anyway just in case.

2022-06-23 02:15 UTC, closed without merging