feat(wp):added support of cashaddr for create address using SDK
BitGo/BitGoJS pull request #1496
Opened 2021-09-08 06:16 UTC by mukeshsp

Jira Ticket : https://bitgoinc.atlassian.net/browse/BG-35555

2021-09-10 04:32 UTC, tylerlevine reviewed
looks good to me, just a slightly tighter type on the new `format` property would be nice

2021-09-10 04:32 UTC, tylerlevine commented on modules/core/src/v2/wallet.ts
> +  format?: string;
```suggestion
  format?: 'base58' | 'cashaddr';
```

2021-09-10 04:32 UTC, tylerlevine requested changes
forgot to request changes, see inline comment

2021-09-10 04:56 UTC, mukeshsp commented on modules/core/src/v2/wallet.ts
> +  format?: string;
updated the changes as suggested.

2021-09-13 18:17 UTC, tylerlevine approved these changes

2021-09-13 18:17 UTC, merged