feat(core): expose compatibility layer at `require('bitgo').bitcoin`
BitGo/BitGoJS pull request #1500
Opened 2021-09-09 10:21 UTC by OttoAllmendinger

For `client-wallet-platform`, we previously exposed the full utxolib
API.

However a small subset is enough:

* `makeRandomKey()`
* `HDNode`
* `hdPath()`
* `address.fromBase58Check()`

Since some of these methods are being deprecated, expose them as
compatibility wrappers around `bip32`.

Issue: BG-34381

2021-09-10 04:46 UTC, tylerlevine requested changes
looks good, small change needed. Do we have any tests to ensure compatibility before removing the old code?

2021-09-10 04:46 UTC, tylerlevine commented on modules/core/src/legacyBitcoin.ts
> +  public static formBase58(str: string): HDNode {
```suggestion
  public static fromBase58(str: string): HDNode {
```

2021-09-10 13:18 UTC, sangaman approved these changes

2021-09-11 00:05 UTC, tylerlevine approved these changes

2021-09-11 00:05 UTC, merged