feat(account lib): Get trx fee limit from statics
BitGo/BitGoJS pull request #1514
Opened 2021-09-14 17:58 UTC by silalvado

get trx fee limit from statics

Jira Ticket:
https://bitgoinc.atlassian.net/browse/STLX-6526

2021-09-14 18:01 UTC, ipelaez-simtlix submitted a review, later dismissed

2021-09-17 06:13 UTC, tylerlevine requested changes
please rebase

2021-09-17 14:28 UTC, ipelaez-simtlix submitted a review, later dismissed

2021-09-17 16:56 UTC, silalvado commented on modules/statics/package.json
> +  "version": "6.13.0-rc.9",
I've updated the version here because of the check-versions script running on the drone

2021-09-17 16:56 UTC, silalvado commented on modules/core/package.json
> +    "@bitgo/statics": "^6.13.0-rc.9",
I've updated the version here because of the check-versions script running on the drone

2021-09-17 17:01 UTC, ipelaez-simtlix reviewed
lgtm

2021-09-17 17:51 UTC, ipelaez-simtlix approved these changes

2021-09-20 12:36 UTC, emiacc approved these changes

2021-09-20 20:13 UTC, tylerlevine requested changes
do not update the versions of internal packages please - this should only be done during the release process

2021-09-20 20:20 UTC, emiacc commented
> do not update the versions of internal packages please - this should only be done during the release process

@tylerlevine 
we need to use the new version of `statics` in `account-lib`
it's because we changed the dependency version in the package.json of `account-lib`
and then realized that the script of check-version failed. 

What is the correct process to do that? should we reference to the old version until a release?

2021-09-21 15:45 UTC, emiacc approved these changes

2021-09-21 16:18 UTC, tylerlevine approved these changes

2021-09-21 19:10 UTC, merged