refactor(account-lib): add calculateForwarderV1Address method
BitGo/BitGoJS pull request #1532
Opened 2021-09-22 14:03 UTC by gianchandania

**Background**

Methods to calculate ethereum forwarder version 1 addresses are being used in bitgo-admin and BitGoJS core module as well. These methods have been added in account-lib, so that they can be used from account lib in both places.

**Changes**

- Added methods `calculateForwarderV1Address()` and `getProxyInitcode()` to calculate forwarder v1 addresses in utils.ts file under eth folder.

- Updated the ethereumjs-util version in order to use `generateAddress2()` method

- Added test for `calculateForwarderV1Address()` method

- Updated the version of @bitgo/statics in order to use constants forwarderImplementationAddress and forwarderFactoryAddress for the test of the above method

Ticket: BG-35735

2021-09-22 16:19 UTC, twtaylorbitgo requested changes
why do we have two versions of ethereumjs utils? this seems kinda nutty to me

2021-09-22 16:31 UTC, gianchandania commented
> why do we have two versions of ethereumjs utils? this seems kinda nutty to me

By two versions, you are referring to 6.2.1 and 6.0.0, right? 6.0.0 is a dependency of ethereumjs-abi and I have updated ethereumjs-util version 5.2.0 to 6.2.1 in order to use generateAddress2 method. I chose 6.2.1 because it is the same version used in microservices for ethereumjs-util. So I thought it would be better to keep the versions in sync in both the repos

2021-09-24 00:02 UTC, ryan-bitgo commented on modules/account-lib/src/coin/eth/utils.ts
> +export function calculateForwarderV1Address(creatorAddress: string, salt: string, initcode: string): string {
i rather we start using buffers directly for parameters. then we don't have to cause from an implementation POV whether it is hex, uft-8, base64, etc... 

but not a blocker

2021-09-24 00:02 UTC, ryan-bitgo commented on modules/account-lib/src/coin/eth/utils.ts
> +export function getProxyInitcode(implementationAddress: string): string {
same with return values, buffers preferred

2021-09-24 00:03 UTC, ryan-bitgo approved these changes
looks fine, added some comments but not blockers.

2021-09-24 15:40 UTC, twtaylorbitgo approved these changes

2021-09-24 15:41 UTC, merged