feat(express): add external API signing to v2 API
BitGo/BitGoJS pull request #1601
Opened 2021-10-22 18:30 UTC by 0xabrarhussain

ticket: BG-38025

```

      ✓ signs p2sh using external api (40ms)

  V2 Wallet External API:
    Transaction Signature Verification
      ✓ should sign a prebuild with external api

  2 passing (95ms)

```

2021-11-02 17:08 UTC, 0xabrarhussain commented on modules/core/test/v2/unit/externalApi.ts
> +        label: 'Signature Verification Wallet',
copied over majority of this from an existing test, but assuming a lot of it isn't required solely for signing logic

2021-11-24 00:37 UTC, tylerlevine requested changes
nice work, this is quite close!

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/src/v2/wallet.ts
> +        return fetch(externalSignerUrl, {
please don't mix promise syntax, let's stick with `yield` for now instead of using `.then()`

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/src/wallet.ts
> +    return Bluebird.resolve(fetch(externalSignerUrl, {
Why use `fetch` instead of `superagent`, which is what we use for making HTTP requests elsewhere in the package?

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/src/v2/wallet.ts
> +      } else {
No need for the `else` here, since the `if` case returns.

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/src/v2/wallet.ts
> +        }).then(response => response.json() as SignedTransaction);
How do we know that this cast is safe? Should we do any validation on the returned object to make sure it looks correct before returning it?

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/unit/externalApi.ts
> +  const userKeypair = {
Please move all this hard coded data into a fixture file

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/unit/externalApi.ts
> +const externalHost = 'https://externalsign.com';
please use an invalid TLD for testing, as per https://datatracker.ietf.org/doc/html/rfc2606#page-2

I prefer `.invalid`

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/unit/externalApi.ts
> +      const firstSignature = '010000000144dea5cb05425f94976e887ccba5686a9a12a3f49710b021508d3d9cd8de16b801000000b600473044022021fa73d5fe61ac8942cd70ff4507c574677ce747de5bc46c3dd2e38ec2448fce022047906
Please move hard coded data to test fixture. Tests should contain only the test logic, and the test data is just noise that isn't relevant to that.

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/unit/externalApi.ts
> +      scope.isDone().should.be.True();
```suggestion
      scope.done();
```

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/unit/externalApi.ts
> +      scope2.isDone().should.be.True();
```suggestion
      scope2.done();
```

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/unit/externalApi.ts
> +      const firstSignature = '010000000144dea5cb05425f94976e887ccba5686a9a12a3f49710b021508d3d9cd8de16b801000000b600473044022021fa73d5fe61ac8942cd70ff4507c574677ce747de5bc46c3dd2e38ec2448fce022047906
Also, these are transactions and not signatures, so this naming is misleading. Also how come we have two separate transactions but only one test?

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/v2/unit/externalApi.ts
> +    const userKeychain = {
Please move hard coded data into fixtures.

2021-11-24 00:37 UTC, tylerlevine commented on modules/core/test/v2/unit/externalApi.ts
> +const externalHost = 'https://externalsign.com';
use invalid TLD here as well.

2021-11-24 00:39 UTC, tylerlevine commented on modules/core/src/v2/wallet.ts
> +        return fetch(externalSignerUrl, {
also same comment as later on about using fetch vs superagent.

2022-06-01 20:15 UTC, closed without merging