fix(statics): use `utxolibName` instead of redefining constants
BitGo/BitGoJS pull request #1722
Opened 2021-11-26 10:19 UTC by OttoAllmendinger

The network constants are already defined in utxolib, there is no need
to repeat them in `statics`.

Also add `BitcoinGoldTestnet`.

Sanity check:

```
» yarn ts-node -e '
import * as utxolib from "@bitgo/utxo-lib";
import { coins, UtxoCoin } from "./src";

for (const name in utxolib.networks) {
  console.log(
    name,
    coins
      .filter((coin => (coin as UtxoCoin).network.utxolibName === name))
      .map(coin => coin.name)
  );
}
'

bitcoin [ 'btc' ]
testnet [ 'tbtc' ]
bitcoincash [ 'bch', 'bcha' ]
bitcoincashTestnet [ 'tbch', 'tbcha' ]
bitcoingold [ 'btg' ]
bitcoingoldTestnet [ 'tbtg' ]
bitcoinsv [ 'bsv' ]
bitcoinsvTestnet [ 'tbsv' ]
dash [ 'dash' ]
dashTest [ 'tdash' ]
litecoin [ 'ltc' ]
litecoinTest [ 'tltc' ]
zcash [ 'zec' ]
zcashTest [ 'tzec' ]
```

Issue: BG-38773

2021-11-28 17:58 UTC, sangaman requested changes
Is this a `fix` or a `refactor`? Curious if this is causing any problems currently. Either way it's good to remove redundant code. I just have one note below.

2021-11-28 17:58 UTC, sangaman commented on modules/statics/src/networks.ts
> +class BitcoinGoldTestnet extends Mainnet implements UtxoNetwork {
Should this extend `Testnet`?

2021-11-28 18:35 UTC, OttoAllmendinger commented on modules/statics/src/networks.ts
> +class BitcoinGoldTestnet extends Mainnet implements UtxoNetwork {
yes!

2021-11-28 18:47 UTC, OttoAllmendinger commented
> Is this a `fix` or a `refactor`? Curious if this is causing any problems currently. Either way it's good to remove redundant code. I just have one note below.

Kind of: I can't really use `@bitgo/statics` in BitGoJS at the moment because we need the objects defined by `utxolib.networks` there (not structural equality but referential equality)

2021-11-29 06:24 UTC, sangaman approved these changes

2021-11-29 08:30 UTC, merged