feat(account-lib): dot optimization
BitGo/BitGoJS pull request #1727
Opened 2021-11-29 14:56 UTC by gibrangul95

@argjv @rliberal-simtlix @jrafael-simtlix @fdmirza

2021-11-29 17:19 UTC, argjv approved these changes

2021-11-29 19:39 UTC, rliberal-simtlix approved these changes

2021-11-29 20:30 UTC, argjv requested changes
Are we now making a call to the node?

2021-12-01 05:04 UTC, gibrangul95 commented
> Are we now making a call to the node?

@argjv no, no calls to the node. Just an internal clean up.

2021-12-02 06:05 UTC, argjv approved these changes

2021-12-02 06:05 UTC, merged