feat(core): allow alphanumeric memoid for eos
BitGo/BitGoJS pull request #1729
Opened 2021-11-30 01:31 UTC by lcovar

There is a current use case where a custodial wallet
wants to send to an alphanumeric memoid for eos.

TICKET: BG-39825

2021-11-30 05:52 UTC, tylerlevine requested changes
looks good, just some minor feedback

2021-11-30 05:52 UTC, tylerlevine commented on modules/core/test/v2/unit/coins/eos.ts
> +    basecoin.isValidMemoId( string257CharsLong).should.equal(false);
please add `@prettier` annotation to this file and run prettier. You have an extra space after the opening paren here.

2021-11-30 05:52 UTC, tylerlevine commented on modules/core/test/v2/unit/coins/eos.ts
> +    const string257CharsLong = '4WMNlu0fFU8N94AwukfpfPPQn2Myo80JdmLNF5rgeKAab9XLD93KUQipcT6US0LRwWWIGbUt89fjmdwpg3CBklNi8QIeBI2i8UDJCEuQKYobR5m4ismm1RooTXUnw5OPjmfLuuajYV4e5cS1jpC6hez5X43PZ5SsGaHNYX2
This should go into the fixtures file.

2021-11-30 23:00 UTC, CapnMigraine approved these changes
lgtm

2021-12-07 03:42 UTC, tylerlevine approved these changes

2021-12-07 03:42 UTC, merged