docs(account-lib): add light copyedit
BitGo/BitGoJS pull request #1733
Opened 2021-11-30 18:45 UTC by gbarr01

add light copyedit

JIRA: BG-36902

2021-11-30 19:05 UTC, gbarr01 commented on modules/account-lib/DEVELOPER.md
> +Accoutn Lib comes with unit tests and it is expected that all changes introduced
typo

2021-11-30 21:11 UTC, tylerlevine requested changes
This repo doesn't support PRs from forks, which is why you are getting the test failures. Please re-create this PR by pushing your branch to this repo and creating the PR from that branch.

2021-11-30 21:40 UTC, gbarr01 commented
> This repo doesn't support PRs from forks, which is why you are getting the test failures. Please re-create this PR by pushing your branch to this repo and creating the PR from that branch.

Thanks, @tylerlevine , I've tried pushing directly but cannot. Do you have any ideas? 

![image](https://user-images.githubusercontent.com/31074572/144132371-daf08a7a-2e4a-4f12-98a4-17965e2e294f.png)

2021-12-01 00:21 UTC, tylerlevine commented
> > This repo doesn't support PRs from forks, which is why you are getting the test failures. Please re-create this PR by pushing your branch to this repo and creating the PR from that branch.
> 
> Thanks, @tylerlevine , I've tried pushing directly but cannot. Do you have any ideas?
> 
> ![image](https://user-images.githubusercontent.com/31074572/144132371-daf08a7a-2e4a-4f12-98a4-17965e2e294f.png)

please open a ticket with the infra team to get added as a contributor to the repo.

2021-12-06 22:59 UTC, closed without merging