fix(ltc): update block explorer link for ltc
BitGo/BitGoJS pull request #1735
Opened 2021-12-01 04:28 UTC by zhongtan912

Ticket: BG-39883

2021-12-01 20:06 UTC, YPAzevedo approved these changes

2021-12-01 20:19 UTC, tylerlevine requested changes
Ticket says the link in the UI goes to `http://explorer.litecoin.net/` which does indeed appear to be down.

But that's not what we have in `statics` here. Are you sure this is the right place to change the explorer URL? Where is the litecoin.net URL coming from?

2021-12-02 00:32 UTC, zhongtan912 commented
> Ticket says the link in the UI goes to `http://explorer.litecoin.net/` which does indeed appear to be down.
> 
> But that's not what we have in `statics` here. Are you sure this is the right place to change the explorer URL? Where is the litecoin.net URL coming from?

Thanks @tylerlevine for highlighting this. Let me investigate further the where the incorrect data is coming from. Will put this in draft for now.

2021-12-03 00:12 UTC, zhongtan912 commented
> > Ticket says the link in the UI goes to `http://explorer.litecoin.net/` which does indeed appear to be down.
> > But that's not what we have in `statics` here. Are you sure this is the right place to change the explorer URL? Where is the litecoin.net URL coming from?
> 
> Thanks @tylerlevine for highlighting this. Let me investigate further the where the incorrect data is coming from. Will put this in draft for now.

Have confirmed that bad data was indeed coming from metadata within lumina submodule. Nonetheless, it would be good to update the explorer link to the one the product team is using (as mentioned in the ticket) to stay in sync

2021-12-03 00:30 UTC, tylerlevine approved these changes

2021-12-03 00:30 UTC, merged