feat(statics): add new tokens
BitGo/BitGoJS pull request #1777
Opened 2021-12-09 19:54 UTC by Joelsx

New token being added ohm, bed, wild, dataecon, ens and ach

STLX-9883

2021-12-10 22:55 UTC, tylerlevine requested changes
please rewrite your commit message subject to describe your changes

2021-12-14 10:42 UTC, Joelsx commented
> please rewrite your commit message subject to describe your changes

done

2021-12-15 00:56 UTC, tylerlevine approved these changes

2021-12-15 00:56 UTC, tylerlevine commented
verified all contract addresses and decimal places against etherscan

2021-12-15 00:56 UTC, merged