chore(account-lib,core): refactor keyDeriver to account-lib
BitGo/BitGoJS pull request #1814
Opened 2021-12-17 23:49 UTC by joey-bai

moves keyDeriver from core to account-lib.
plan is to leverage this code to implement address derivation for
Ed25519KeyPair

Ticket: STLX-10000

2021-12-20 19:24 UTC, rliberal-simtlix approved these changes

2021-12-20 23:29 UTC, tylerlevine requested changes
Looks fine but I think it's missing a lockfile update

2021-12-21 16:57 UTC, joey-bai commented
> Looks fine but I think it's missing a lockfile update

@tylerlevine doesn't look like package-lock is being tracked for core and account lib.
https://github.com/BitGo/BitGoJS/tree/master/modules/account-lib
https://github.com/BitGo/BitGoJS/tree/master/modules/core

2021-12-21 17:30 UTC, tylerlevine approved these changes
No package lock updates needed

2021-12-21 17:47 UTC, merged