feat(account-lib): add key factory for coins
BitGo/BitGoJS pull request #1826
Opened 2021-12-23 08:02 UTC by byhow

Ticket: STLX-10821

2021-12-27 12:01 UTC, jrafael-simtlix commented on modules/account-lib/src/keyPair/index.ts
> +  return {} as BaseKeyPair;
If a coin is not find, do we return empty object?
How does user handle this case?
Also there are no test case about this behavior.

2022-01-03 22:47 UTC, 0xabrarhussain requested changes
this change seems pretty wonky. this makes the convention assumption that everything in the folder above only has coin modules with the same structure

which sure you can have that convention, but it wont' be enforced

2022-01-04 01:32 UTC, byhow commented
@0xabrarhussain The structure is not enforced in that we will implement the interface gradually if such structure is needed. For an initial factory method that gets the corresponding `key` implementation of each coin, we are not looking to refactor all of the previous coins' export structure.

For the exports module, it is checking if the structure exported the baseKey class implementation, so it does not need to follow the same structure, but only need to export that specific `key` module.

That being said, we are open to better ways to group the `key` class implementations without refactoring the old codebase for sure.

2022-01-04 01:33 UTC, byhow commented
ref on the additional unit tests audits: https://github.com/BitGo/BitGoJS/pull/1832

2022-01-05 22:11 UTC, byhow commented
@0xabrarhussain Do you mind we move this conversation over to #1832? And then we can close this in favor of the other PR

2022-01-05 23:38 UTC, byhow commented
closing in favor of the other PR

2022-01-05 23:38 UTC, closed without merging