feat(core): add examples of enable and disable token
BitGo/BitGoJS pull request #1972
Opened 2022-02-09 19:01 UTC by JoaquinTissera-Simtlix

add examples of enable and disable token

STLX-13257

2022-02-10 12:36 UTC, JulioAchaval-SimTLiX requested changes

2022-02-10 12:36 UTC, JulioAchaval-SimTLiX commented on modules/core/example/js/algo/account-disable-token.js
> +    console.dir(txEnableToken, { depth: 6 });
```suggestion
    const txDisableToken = yield wallet.sendMany({
      type: 'disabletoken',
      recipients: [
        {
          amount: '0',
          address: address,
        },
      ],
      feeRate: 1,
      walletPassphrase,
      closeRemainderTo,
    });
    console.dir(txDisableToken, { depth: 6 });
```

2022-02-17 15:44 UTC, nicolasbellanich-simtlix commented on modules/core/example/ts/algo/disable-token.ts
> +// change this to 'algo' when you are ready for production
```suggestion
// change this to 'algo:16026733' when you are ready for production
```

2022-02-17 15:49 UTC, nicolasbellanich-simtlix commented on modules/core/example/ts/algo/disable-token.ts
> +async function main() {
Since it's TS , you should add return type
```suggestion
async function main() : void {
```

2022-02-17 15:59 UTC, JulioAchaval-SimTLiX submitted a review, later dismissed

2022-02-17 16:00 UTC, nicolasbellanich-simtlix commented on modules/core/example/ts/algo/disable-token.ts
> +    throw new Error();
Void error message it's maybe something we don't want to face in future
```suggestion
    throw new Error('Did not unlock');
```

2022-02-17 16:01 UTC, nicolasbellanich-simtlix commented on modules/core/example/ts/algo/enable-token.ts
> +// change this to 'algo' when you are ready for production
Same as above

2022-02-17 16:02 UTC, nicolasbellanich-simtlix commented on modules/core/example/ts/algo/enable-token.ts
> +    throw new Error();
Same as above

2022-02-17 16:03 UTC, JulioAchaval-SimTLiX commented on modules/core/example/ts/algo/disable-token.ts
> +    throw new Error();
```suggestion
    throw new Error('We did not unlock.');
```

2022-02-17 16:03 UTC, JulioAchaval-SimTLiX commented on modules/core/example/ts/algo/disable-token.ts
> +    throw new Error();
Try to avoid console.log when you throw an error

2022-02-17 16:04 UTC, nicolasbellanich-simtlix requested changes
Leave some comments here

2022-02-17 16:20 UTC, nicolasbellanich-simtlix submitted a review, later dismissed

2022-02-17 17:43 UTC, nicolasbellanich-simtlix approved these changes
LGTM

2022-02-17 17:48 UTC, JulioAchaval-SimTLiX approved these changes

2022-02-17 19:13 UTC, lcovar approved these changes

2022-02-17 19:14 UTC, merged