feat(root): add unit-test-all to ci
BitGo/BitGoJS pull request #2029
Opened 2022-02-17 21:23 UTC by byhow

On package updates, the current CI won't prevent breaking changes with running all unit tests but instead relies on running unit test diff. Making this mandatory only when package.json updates in this PR.

There isn't really a quick native way to run jobs on file changes without relying on 3rd party actions. Instead, a new workflow file is introduced. Ref: https://github.community/t/is-it-possible-to-run-the-job-only-when-a-specific-file-changes/115484/10

Ticket: BG-00000

2022-02-22 16:25 UTC, tylerlevine submitted a review, later dismissed
seems pretty reasonable to me as long as we're not running this all the time.

It might also be good to run this without any lockfiles present - that would replicate the versions that a client would get if they installed the package from npm. That's not in scope here though but could be done as a separate change

2022-02-22 19:34 UTC, byhow commented
@tylerlevine Thanks for the review! I need to revert the intentional package update to show/test the triggered ci, so I applied the changes you suggested to remove the lock file as well. Hopefully it looks good now!

2022-02-23 00:24 UTC, tylerlevine requested changes
sorry I might be blind but where are the lock files getting removed as you said?

2022-02-23 01:53 UTC, byhow commented
@tylerlevine Ah sorry I thought it was to remove `yarn.lock` from the checklist to still skip the unit tests when changes apply to that file. If you meant to remove the `--with-frozen-lockfile` flag, I can remove that and put back the yarn lock file.

2022-03-09 04:05 UTC, tylerlevine commented
> @tylerlevine Ah sorry I thought it was to remove `yarn.lock` from the checklist to still skip the unit tests when changes apply to that file. If you meant to remove the `--with-frozen-lockfile` flag, I can remove that.

no, what I meant was a CI run that does `rm yarn.lock` before installing and running the tests. This would create an install which contains the same set of packages that a downstream user of the packages would get (since they install the latest allowable version of each package, as determined by their semver ranges).

2022-03-09 06:32 UTC, byhow commented
Thanks @tylerlevine for the further clarification. I added the `rm yarn.lock` step before the install, hopefully that addresses your comment. I also test triggered the ci by modifying some arbitrary `package.json` in `modules` as well.

2022-03-09 06:33 UTC, byhow commented on .github/workflows/test_package_updates.yml
> +        run: rm yarn.lock
the remove lock file step here ^

2022-03-14 20:53 UTC, tylerlevine approved these changes
thanks for doing this @byhow!

2022-03-14 20:53 UTC, merged