feat: external signer to read encrypted privkeys
BitGo/BitGoJS pull request #2069
Opened 2022-03-03 19:57 UTC by DariusParvin

- When running in external signer mode, express will expect the private
key json file to be in the encrypted format (same as on the keycard but
with escape characters).
- Express expects the wallet passphrase to be set in the environment
  with the name `WALLET_<walletId>_PASSPHRASE`

Ticket: BG-43925

2022-03-07 20:25 UTC, tylerlevine requested changes
good work, just a few comments

2022-03-07 20:25 UTC, tylerlevine commented on modules/express/src/clientRoutes.ts
> +  express;
what's this?

2022-03-07 20:25 UTC, tylerlevine commented on modules/express/src/clientRoutes.ts
> +  const bg = new BitGo();
pass bitgo object in as param - it's available in the calling scope as `req.bitgo` (see line 405)

2022-03-07 20:25 UTC, tylerlevine commented on modules/express/src/clientRoutes.ts
> +    return decrypted;
```suggestion
    return bg.decrypt({ password: walletPw, input: encryptedPrivKey });
```

2022-03-07 20:25 UTC, tylerlevine commented on modules/express/src/clientRoutes.ts
> +    return await coin.signTransaction({ ...req.body, ...{ prv: privKey } });
literal destruction is redundant here
```suggestion
    return await coin.signTransaction({ ...req.body, prv: privKey });
```

2022-03-07 20:45 UTC, DariusParvin commented on modules/express/src/clientRoutes.ts
> +  express;
that was unintentional. removed

2022-03-07 20:47 UTC, DariusParvin commented
Good catches, thanks for the feedback. I've addressed them now

2022-03-08 00:20 UTC, tylerlevine approved these changes

2022-03-08 00:25 UTC, merged