STLX-13577-feat(wallet-platform): add emergency param to whitelist
BitGo/BitGoJS pull request #2085
Opened 2022-03-08 13:34 UTC by nicolasbellanich-simtlix

:x:  DO NOT MERGE :x: 

[stlx-13577](https://bitgoinc.atlassian.net/browse/STLX-13577)

2022-03-28 13:45 UTC, charly-simtlix requested changes

2022-03-28 13:45 UTC, charly-simtlix commented on modules/core/src/v2/wallet.ts
> +      'emergency',
Please document field use

2022-03-28 18:04 UTC, JulioAchaval-SimTLiX commented on modules/core/src/v2/wallet.ts
> +      'emergency',
Adding

2022-03-28 18:42 UTC, charly-simtlix approved these changes

2022-03-29 15:31 UTC, mmcshinsky-bitgo approved these changes

2022-03-29 15:31 UTC, merged