chore: update express API link in readme
BitGo/BitGoJS pull request #2103
Opened 2022-03-14 21:07 UTC by pranavjain97

Was exploring SDK and Express, and found the current README link we have for express API is broken. 
I'm guessing this is the new one? - https://api.bitgo.com/docs/#tag/Express

2022-03-14 21:21 UTC, tylerlevine requested changes
thanks for the fix! We should link to the app subdomain though

2022-03-14 21:21 UTC, tylerlevine commented on modules/express/README.md
> +Comprehensive documentation on the APIs provided by BitGo Express can be found at our [Platform API Reference](https://api.bitgo.com/docs/#tag/Express).
```suggestion
Comprehensive documentation on the APIs provided by BitGo Express can be found at our [Platform API Reference](https://app.bitgo.com/docs/#tag/Express).
```

2022-03-22 22:31 UTC, mmcshinsky-bitgo approved these changes

2022-03-25 15:26 UTC, tylerlevine approved these changes

2022-03-25 15:27 UTC, merged