Stlx 14831 withdraw builder
BitGo/BitGoJS pull request #2148
Opened 2022-03-29 15:24 UTC by facundoCarreSimtlix

2022-03-29 15:40 UTC, ipelaez-simtlix requested changes
Lets use stakingActivate as reference and add checks to intput and output on some unit tests here.

2022-03-29 15:40 UTC, ipelaez-simtlix commented on modules/account-lib/src/coin/near/stakingWithdrawBuilder.ts
> +    this.contractCallWrapper.deposit = '0'; //
delete that // , lets delete also same thing on Deactivate Builder

2022-03-31 11:57 UTC, silalvado requested changes

2022-03-31 11:57 UTC, silalvado commented on modules/account-lib/src/coin/near/stakingWithdrawBuilder.ts
> +  private contractCallWrapper;
type is missing

2022-03-31 11:57 UTC, silalvado commented on modules/account-lib/test/unit/coin/near/transactionBuilder/stakingWithdrawBuilder.ts
> +    it('should fail to staking withdraw with missing gas', async () => {
This shouldn't be inside succeed describe

2022-03-31 11:57 UTC, silalvado commented on modules/account-lib/src/coin/near/stakingWithdrawBuilder.ts
> +  private contractCallWrapper;
Type is missing

2022-03-31 11:57 UTC, silalvado commented on modules/account-lib/test/unit/coin/near/transactionBuilder/stakingWithdrawBuilder.ts
> +    it('should fail to staking withdraw with missing amount', async () => {
This shouldn't be inside succeed describe

2022-03-31 11:57 UTC, silalvado commented on modules/account-lib/test/unit/coin/near/transactionBuilder/stakingWithdrawBuilder.ts
> +    it('build from an signed staking withdraw', async () => {
replace an with a

2022-03-31 11:57 UTC, silalvado commented on modules/account-lib/src/coin/near/transaction.ts
> +        const unit8ArrayToString = Buffer.from(action.functionCall.args).toString();
unnecessary constant

2022-03-31 14:28 UTC, ipelaez-simtlix approved these changes
I have added some code here but I had request changes before so I need approve to unock this PR

2022-03-31 17:33 UTC, rliberal-simtlix commented on modules/account-lib/src/coin/near/stakingWithdrawBuilder.ts
> +   * @param {string} value the amount in the minimum unit (yocto) of this transaction
specifgy here number of decimals.

2022-03-31 17:59 UTC, silalvado approved these changes

2022-03-31 18:48 UTC, rliberal-simtlix approved these changes

2022-03-31 20:41 UTC, merged