chore(examples): add token transaction example
BitGo/BitGoJS pull request #2240
Opened 2022-04-29 01:41 UTC by shiksb

Add an example of how to build, sign, and send a token transaction.

2022-05-03 21:25 UTC, jicli approved these changes

2022-05-04 22:15 UTC, mmcshinsky-bitgo requested changes

2022-05-04 22:15 UTC, mmcshinsky-bitgo commented on modules/bitgo/example/ts/send-token-transaction.ts
> +  const rawHalfSignedTransaction: string = (halfSignedTransaction as any).halfSigned.txHex;
Lgtm :) Can we update the `any` to the appropriate type?

2022-05-04 22:18 UTC, mmcshinsky-bitgo commented on modules/bitgo/example/ts/send-token-transaction.ts
> +  const rawHalfSignedTransaction: string = (halfSignedTransaction as any).halfSigned.txHex;
Also needs JavaScript equivalent example.

2022-06-30 02:15 UTC, closed without merging