feat(wallet-platform): add openApi doc for transaction with emergency…
BitGo/BitGoJS pull request #2332
Opened 2022-06-02 20:16 UTC by nicolasbellanich-simtlix

Add openApi doc for transaction with emergency param

stlx-16868

2022-06-02 22:06 UTC, mmcshinsky-bitgo requested changes

2022-06-02 22:06 UTC, mmcshinsky-bitgo commented on modules/bitgo/example/ts/algo/transaction-with-emergency-param.ts
> +import { BitGo, Wallet } from 'bitgo';
Missing title comments. See other examples.

2022-06-02 22:06 UTC, mmcshinsky-bitgo commented on modules/bitgo/example/ts/algo/transaction-with-emergency-param.ts
> +// this will need to be a real OTP code on production
Possible disclosure as optional?

2022-06-08 14:09 UTC, JulioAchaval-SimTLiX approved these changes

2022-06-09 17:26 UTC, mmcshinsky-bitgo commented on modules/bitgo/example/ts/algo/transaction-with-emergency-param.ts
> +import { BitGo, Wallet } from 'bitgo';
Let's add `Copyright 2020, BitGo, Inc.  All Rights Reserved.` and we're good to go (for consistency).

2022-06-09 19:28 UTC, tylerlevine submitted a review, later dismissed
also one other note - there's no OpenAPI doc in here so I'm not sure why that's being mentioned in the commit message

2022-06-09 19:28 UTC, tylerlevine commented on modules/bitgo/example/ts/algo/transaction-with-emergency-param.ts
> +    emergency: true,
I'm curious why we didn't add a `validityWindow` param or something more useful than a boolean for either 1 or 2 hours, but that ship has sailed at this point.

Thanks for adding the example 👍

2022-06-13 21:43 UTC, mmcshinsky-bitgo approved these changes

2022-06-13 21:43 UTC, merged