feat(sdk-coin-avaxp): implement generateKeyPair and signTransaction
BitGo/BitGoJS pull request #2411
Opened 2022-06-22 14:41 UTC by jrafael-simtlix

STLX-17279

2022-06-22 16:04 UTC, ducnguyen-bitgo commented
@jrafael-simtlix Since there's already a `avaxp.ts` file [here](https://github.com/BitGo/BitGoJS/blob/STLX-17279-bitgo-sdk-implement-generate-key-pair-and-sign-transaction-in-bitgo-module/modules/bitgo/src/v2/coins/avaxp.ts). Could you git mv it to the sdk-coin-avaxp package so we could keep track of the git history? Also, once you move it to the coin package, could you import and re-export it [here](https://github.com/BitGo/BitGoJS/blob/STLX-17279-bitgo-sdk-implement-generate-key-pair-and-sign-transaction-in-bitgo-module/modules/bitgo/src/v2/coins/index.ts#L5) like how we did it for algo and cspr for backward compatibility? Thanks!

2022-06-22 16:13 UTC, mmcshinsky-bitgo commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +import * as AccountLib from '../../src/lib';
Let's change this to AvaxpLib for consistency

2022-06-22 17:34 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +import * as testData from '../resources/avaxp';
Resources's merged in a preview PR.

2022-06-22 17:45 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +      // TODO
Done

2022-06-22 17:45 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +      // TODO
Done

2022-06-22 17:46 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +    // TODO: Implement later.
Remove comment when avaxp from bitgo modules merge with this.

2022-06-22 17:46 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +    // TODO: Implement when available on the SDK.
Remove comment when avaxp from bitgo modules merge with this.

2022-06-22 17:47 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +import * as Lib from './lib';
Done, also in unittest

2022-06-22 17:47 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/src/index.ts
> +export * from './avaxp';
Add it

2022-06-22 21:16 UTC, mmcshinsky-bitgo requested changes

2022-06-22 21:16 UTC, mmcshinsky-bitgo commented on modules/bitgo/package.json
> +    "@bitgo/sdk-coin-avaxp": "^1.0.0",
Add coin to tsconfig as well

2022-06-23 00:41 UTC, shiksb commented on modules/bitgo/package.json
> +    "@bitgo/sdk-coin-avaxp": "^1.0.0",
added

2022-06-23 15:16 UTC, mmcshinsky-bitgo approved these changes

2022-06-23 15:16 UTC, merged