chore: ofcerc20 for HUM HXRO IMX INJ
BitGo/BitGoJS pull request #2477
Opened 2022-07-06 18:56 UTC by davidlin2-bitgo

Ticket: BG-51594

2022-07-06 19:00 UTC, drew-bitgo requested changes

2022-07-07 01:30 UTC, davidlin2-bitgo commented on modules/statics/src/coins.ts
> +  ofcerc20('ofcimx', 'Immutable X', 18, UnderlyingAsset.IMX),
we're using v2.

2022-07-07 01:32 UTC, drew-bitgo approved these changes

2022-07-07 14:16 UTC, drew-bitgo approved these changes

2022-07-07 15:23 UTC, mmcshinsky-bitgo submitted a review, later dismissed

2022-07-07 16:30 UTC, tylerlevine submitted a review, later dismissed
commits are not properly signed and cannot be merged until they are fixed. Please take a look

2022-07-15 01:29 UTC, drew-bitgo approved these changes

2022-07-15 17:37 UTC, drew-bitgo approved these changes

2022-07-15 17:54 UTC, mmcshinsky-bitgo approved these changes

2022-07-15 17:54 UTC, merged