chore(statics): update Sol coin name to Solana BG-53009
BitGo/BitGoJS pull request #2565
Opened 2022-07-22 14:26 UTC by michael-gallegos-bg

Update "Sol" and "Testnet Sol" in statics to be the full names "Solana" and "Testnet Solana"

Ticket: https://bitgoinc.atlassian.net/browse/BG-53009

2022-07-22 15:44 UTC, joey-bai submitted a review, later dismissed

2022-07-22 16:36 UTC, mmcshinsky-bitgo requested changes
This is a breaking change and will need to be reflected as such in the commit: https://www.conventionalcommits.org/en/v1.0.0/

2022-07-25 14:36 UTC, michael-gallegos-bg commented
Hi @mmcshinsky-bitgo, I updated the commit to include that this is a breaking change. Can you please confirm that the formatting is correct? Thanks very much!

2022-07-25 16:00 UTC, michael-gallegos-bg commented
> > Hi @mmcshinsky-bitgo, I updated the commit to include that this is a breaking change. Can you please confirm that the formatting is correct? Thanks very much!
> 
> Yup, that looks correct, though somehow the BG- is missing on the next line down in the commit footer.

Should be fixed!

2022-07-25 16:05 UTC, mmcshinsky-bitgo approved these changes

2022-07-25 16:29 UTC, merged