fix(abstract-utxo): remove unused UnspentParams and AddressInfo
BitGo/BitGoJS pull request #2619
Opened 2022-08-04 17:47 UTC by williamqin-bitgo

2022-08-08 23:29 UTC, lcovar submitted a review, later dismissed

2022-08-09 02:26 UTC, mmcshinsky-bitgo requested changes
These are breaking changes and will need to be documented in the commit footer.

2022-08-09 16:42 UTC, lcovar approved these changes

2022-08-09 16:45 UTC, mmcshinsky-bitgo approved these changes

2022-08-09 20:05 UTC, merged

2022-08-09 20:07 UTC, mmcshinsky-bitgo commented
@williamqin-bitgo I noticed last second that the commit footer wasn't `BREAKING CHANGE`. Would you be able to amend your commit as another quick PR?