feat(account-lib): add support for additional hash algorithms
BitGo/BitGoJS pull request #2696
Opened 2022-08-26 16:21 UTC by sachushaji

this change adds support for additional
hashing algorithms for ecdsa tss

TICKET: BG-55978

2022-08-26 16:51 UTC, olibeyene requested changes
lgtm! just one thing

2022-08-26 16:51 UTC, olibeyene commented on modules/sdk-core/src/account-lib/mpc/tss/ecdsa/ecdsa.ts
> +    const m = (hash || createHash('sha256')).update(M).digest();
can you change the default hash function to Keccak?

2022-08-26 19:26 UTC, olibeyene approved these changes

2022-08-29 16:37 UTC, johnoliverdriscoll approved these changes

2022-08-29 17:08 UTC, byhow approved these changes

2022-08-29 17:09 UTC, merged