fix(bitgo): remove address param from lightning().deposit
BitGo/BitGoJS pull request #2764
Opened 2022-09-14 18:10 UTC by jamalchowdhury-bitgo-github

Removed `address` param for `lightning().deposit` from SDK because there is no easy way to check if address is lightning address. A user could potentially provide an arbitrary, non-lightning address which we’d send funds to and end up not adding anything to the wallet’s custodial lightning balance

Ticket: BG-57388

2022-09-14 19:02 UTC, sangaman requested changes

2022-09-14 19:02 UTC, sangaman commented on modules/sdk-core/src/bitgo/lightning/lightning.ts
> +    const res = await this.wallet.send({ amount });
We still need to specify an address when we send coins, we just want to make sure that we use `createDepositAddress` to get the address.

2022-09-16 16:09 UTC, sangaman approved these changes
TY!

2022-09-16 16:12 UTC, mmcshinsky-bitgo approved these changes

2022-09-16 16:12 UTC, merged