feat(sdk-coin-polygon): support tss in polygon controller
BitGo/BitGoJS pull request #2771
Opened 2022-09-15 20:19 UTC by kxl4126

Ticket: BG-57512

## Description

## Issue Number

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code compiles correctly for both Node and Browser environments
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My commits follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and I have properly described any BREAKING CHANGES
- [ ] The ticket or github issue was included in the commit message as a reference
- [ ] I have made corresponding changes to the documentation and on any new/updated functions and/or methods - [jsdoc](https://jsdoc.app/)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-09-15 22:05 UTC, byhow approved these changes, later dismissed

2022-09-15 22:12 UTC, mmcshinsky-bitgo requested changes
Need to add `STAKING` feature to polygon in statics/coins. `ETH_FEATURES_WITH_STAKING` seems to match the criteria.

2022-09-15 22:48 UTC, mmcshinsky-bitgo approved these changes

2022-09-16 15:05 UTC, mmcshinsky-bitgo approved these changes

2022-09-16 15:05 UTC, merged