feat(sdk-core): parse zero value lightning invoices
BitGo/BitGoJS pull request #2805
Opened 2022-09-22 15:45 UTC by sangaman

## Description

This allows for parsing/decoding zero value lightning invoices, which can be used for requesting a payment for any amount.

This commit also refactors existing code to use consistent variable capitalization for `millisatoshis` and to improve comments for invoice types.

## Issue Number

Ticket: BG-57634

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested manually and with a new mocha test case.

2022-09-22 16:36 UTC, brandonblack requested changes
I can't readily tell what is the functional change vs. renaming and improving consistency. Can you split it into 2 commits?

2022-09-22 17:52 UTC, sangaman commented
@brandonblack I split this into two commits like you said, and also fixed up an issue with the tests.

2022-09-22 21:47 UTC, brandonblack approved these changes

2022-09-23 15:03 UTC, sangaman commented
Build fixed, it was just a minor issue arising from splitting the commits.

2022-09-23 15:09 UTC, brandonblack approved these changes

2022-09-23 17:56 UTC, mmcshinsky-bitgo approved these changes

2022-09-23 17:56 UTC, merged