feat(express): support routes to prebuildAndSignTransaction
BitGo/BitGoJS pull request #2809
Opened 2022-09-23 09:29 UTC by aaldemir

## Description

Adds Express endpoint and handler.
Add endpoint and handler for request which are meant to be routed to sdk-core prebuildAndTransaction.
This express endpoint will be useful for customers with TSS wallets trying to send funds and transfer tokens.

This is part of a broader task to support NFT transfers for Polygon TSS wallets (and other EVM-coin TSS wallets).

## Issue Number

JIRA ticket: BG-58191 subtask of https://bitgoinc.atlassian.net/browse/BG-57934

## Type of change

- [*] New feature (non-breaking change which adds functionality)
- [*] This change requires a documentation update

# How Has This Been Tested?

Unit test which stubs async calls to Platform. Checks the request flows through properly and stubbed response is returned properly.

# Checklist:
all have been checked (and removed from description)

2022-09-23 09:34 UTC, aaldemir commented
@islamaminBitGo please take a look given your changes for BG-53481

2022-09-23 09:39 UTC, aaldemir commented
@shiksb please take a look since you are familiar with the scripts used to send from TSS wallet

2022-10-07 18:52 UTC, shiksb requested changes

2022-10-07 18:52 UTC, shiksb commented on modules/express/src/clientRoutes.ts
> +  );
Can we stay consistent with the handler names of the other routes. Something like 
```suggestion
    '/api/v2/:coin/wallet/:id/prebuildAndSignTransaction',
    parseBody,
    prepareBitGo(config),
    promiseWrapper(handleV2PrebuildAndSignTransaction)
  );
```

2022-10-07 19:27 UTC, shiksb approved these changes

2022-10-07 19:29 UTC, merged