refactor: tweak names of some Unspent types
BitGo/BitGoJS pull request #2934
Opened 2022-10-24 13:51 UTC by OttoAllmendinger

Change NonWitnessUnspent to UnspentWithPrevTx, reflecting the
structure a little bit better. This cleans up a double negation in the
code.

Issue: BG-47824

2022-10-25 16:34 UTC, davidkaplanbitgo approved these changes, later dismissed

2022-10-25 17:51 UTC, mmcshinsky-bitgo requested changes
LGTM. Needs BREAKING CHANGE: description in commit footer.

2022-10-26 14:50 UTC, OttoAllmendinger commented
updated

2022-10-26 15:11 UTC, mmcshinsky-bitgo approved these changes

2022-10-26 16:32 UTC, merged