feat(avaxp): Update Verify Transaction to Support Exports
BitGo/BitGoJS pull request #2968
Opened 2022-11-01 02:25 UTC by colin-y-wu

Ticket: BG-55597

## Description

Ticket: BG-55597

Update verify transaction to support export from P-chain

## Issue Number

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code compiles correctly for both Node and Browser environments
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My commits follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and I have properly described any BREAKING CHANGES
- [ ] The ticket or github issue was included in the commit message as a reference
- [ ] I have made corresponding changes to the documentation and on any new/updated functions and/or methods - [jsdoc](https://jsdoc.app/)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-11-01 18:43 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          throw new Error('Stake Tx does not required recipients');
nit: typo
```suggestion
          throw new Error('Stake Tx does not require recipients');
```

2022-11-01 18:45 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +            address: EXPORT_P_2_C.pAddresses.join('~'),
The export P 2 C recipients address should be a C Address.

2022-11-01 18:48 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          if (!totalAmount.isEqualTo(explainedTx.outputAmount)) {
@CapnMigraine Are we  going to estimate import C fee to be add it in the export amount?

2022-11-02 10:43 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +            address: EXPORT_P_2_C.pAddresses.join('~'),
The recipients in export P 2 C is a C wallet. The export is target the sender addresses, so the import is do it by the same wallet. The export has the recipients address in the memo, we could check that.

2022-11-04 01:39 UTC, jicli commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          const filteredRecipients = [{ address: stakingOptions?.nodeID, amount: stakingOptions?.amount }];
staking options should not be `?` ? as it will always be there for `addValidator` (if i remember correctly )

2022-11-04 01:41 UTC, jicli commented on modules/sdk-coin-avaxp/src/avaxp.ts
>          if (!params.txParams.recipients || params.txParams.recipients.length === 0) {
```suggestion
        if (!params.txParams.recipients || params.txParams.recipients.length === 0) {}
        validateStakingTx(params);
```

2022-11-04 01:46 UTC, jicli commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +            throw new Error('Tx total amount does not match with expected total amount field');
```suggestion
            throw new Error('Tx total amount ${totalamount} does not match with expected total amount field ${explainedTx.outputAmount}');
```

2022-11-04 01:46 UTC, jicli commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +            throw new Error('Invalid P-chain address');
```suggestion
            throw new Error('Invalid P-chain address ${explainedTx.outputs[0].address}');
```

2022-11-04 01:47 UTC, jicli commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          throw new Error('Invalid C-chain receive address, does not match expected params address');
same as above

2022-11-07 16:32 UTC, mmcshinsky-bitgo commented
@colin-y-wu You'll need to rebase this PR to fix the failed test.

2022-11-07 19:10 UTC, mmcshinsky-bitgo commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +  validateStakingTx(
Can we get documentation (jsdocs) for these methods?

2022-11-08 10:13 UTC, jrafael-simtlix commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          this.validateExportTx(params.txParams.recipients, memo?.value, explainedTx);
Please, check memo exist, like you do with recipients. 

We have a technical debt 
https://bitgoinc.atlassian.net/browse/BG-56877

2022-11-09 21:13 UTC, CapnMigraine requested changes

2022-11-09 21:13 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +      console.log(explainedTx.memo);
remove

2022-11-09 21:40 UTC, CapnMigraine approved these changes

2022-11-09 21:41 UTC, merged