feat(root): will update isValidAddress fn to support ecash address formats
BitGo/BitGoJS pull request #2993
Opened 2022-11-08 09:10 UTC by rushilbg

BG-60666

2022-11-08 09:15 UTC, OttoAllmendinger requested changes
you should call the PR title "use utxolib toOutputScriptTryFormats in `isValidAddress`"

The fact that ecash addresses are now supported is more of a side effect (I believe this PR also enables cashaddr support for coin `bch`)

2022-11-08 09:15 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/config.ts
> +// an array of valid coins for recipient wallets of the original accidental/unintentional deposit.
let's do this in a separate PR

2022-11-08 10:16 UTC, rushilbg commented on modules/abstract-utxo/src/config.ts
> +// an array of valid coins for recipient wallets of the original accidental/unintentional deposit.
Removed

2022-11-08 10:40 UTC, OttoAllmendinger commented
Background: we moved all address parsing logic, including support for nonstandard formats, to `utxolib.addressFormat` a while ago. BitGoJS still implemented custom address validation in `isValidAddress()` which is slightly inconsistent.

This change now has these changes for `isValidAddress()` 

* rejects legacy litecoin addresses (3-prefixed)
* accept `bitcoincash:` cashaddrs for the `bch` coin
* accept `ecash:` cashaddrs for the `bcha` coin

2022-11-08 19:58 UTC, OttoAllmendinger approved these changes

2022-11-09 03:40 UTC, OttoAllmendinger requested changes

2022-11-09 03:40 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
>    isValidAddress(address: string, forceAltScriptSupport = false): boolean {
let's put support for non-defined formats behind a parameter

```suggestion
  isValidAddress(address: string, param?: { anyFormat: boolean } | /* legacy parameter */ boolean): boolean {
    if (typeof param === 'boolean' && param) {
      throw new Error('deprecated');
    }
    
    const formats = (param && param.anyFormat) ? ['default'] : undefined;
    
     try {
        utxolib.addressFormat.toOutputScriptTryFormats(address, this.network, formats);
        return true;
      } catch (e) {
        return false;
      }
  }  
```

2022-11-09 12:31 UTC, OttoAllmendinger approved these changes

2022-11-09 12:49 UTC, merged