feat(utxo-lib): show parseAddress info for bech32(m), cashaddress
BitGo/BitGoJS pull request #3041
Opened 2022-11-22 14:25 UTC by OttoAllmendinger

Issue: BG-60311

2022-11-22 16:28 UTC, brandonblack requested changes
Changes look good, but commit message / PR title say `utxo-lib` when they mean `utxo-bin`. Nice.

2022-11-23 05:49 UTC, OttoAllmendinger commented
oops, fixed

2022-11-29 16:34 UTC, brandonblack approved these changes

2022-11-29 17:25 UTC, byhow approved these changes

2022-11-30 04:55 UTC, merged