feat(sdk-coin-avaxp): Verify import in P
BitGo/BitGoJS pull request #3055
Opened 2022-11-25 21:31 UTC by colin-y-wu

Ticket: BG-55596

2022-11-28 17:47 UTC, mmcshinsky-bitgo requested changes

2022-11-28 17:47 UTC, mmcshinsky-bitgo commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +  validateImportInP(explainedTxInputs: AvaxpLib.AvaxpEntry[], txParams: AvaxpTransactionParams): void {
Can we get documentation for this method?

2022-11-28 17:58 UTC, CapnMigraine reviewed
Please fix the commit message and PR description to reference ticket [BG-55595](https://bitgoinc.atlassian.net/browse/BG-55595)

2022-11-28 18:07 UTC, CapnMigraine requested changes

2022-11-28 18:07 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          // ImportInC
clarification-nit:
```suggestion
          // Import to C-chain
```

2022-11-28 18:07 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          // ImportInP
clarification-nit:
```suggestion
          // Import to P-chain
```

2022-11-28 18:07 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +          this.validateImportInP(explainedTx.inputs, params.txParams);
consistency-nit:
Please avoid using export "in" and import "in"
```suggestion
          this.validateImportTx(explainedTx.inputs, params.txParams);
```

2022-11-28 18:07 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +    it('should succeed to verify import in P transaction', async () => {
```suggestion
    it('should succeed to verify import to P transaction', async () => {
```

2022-11-28 18:07 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/test/unit/avaxp.ts
> +    it('should fail to verify import in P transaction with wrong unspents', async () => {
```suggestion
    it('should fail to verify import to P transaction with wrong unspents', async () => {
```

2022-11-28 18:07 UTC, CapnMigraine commented on modules/sdk-coin-avaxp/src/avaxp.ts
> +  validateImportInP(explainedTxInputs: AvaxpLib.AvaxpEntry[], txParams: AvaxpTransactionParams): void {
consistency-nit:
```suggestion
  validateImportTx(explainedTxInputs: AvaxpLib.AvaxpEntry[], txParams: AvaxpTransactionParams): void {
```

2022-11-29 16:10 UTC, CapnMigraine approved these changes

2022-11-29 16:53 UTC, mmcshinsky-bitgo approved these changes

2022-11-30 17:02 UTC, merged