add valueString to unspents for doge recovery flow
BitGo/BitGoJS pull request #3057
Opened 2022-11-28 14:22 UTC by Phani024

add valueString to unspents for doge recovery flow

Ticket: [BG-62721](https://bitgoinc.atlassian.net/browse/BG-62721)

2022-11-29 09:24 UTC, OttoAllmendinger requested changes

2022-11-29 09:24 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/recovery/backupKeyRecovery.ts
> +  }
Remove the branching, always put `valueString` on the unspents. This will simplify the return type as well.

2022-11-29 09:39 UTC, dpkjnr approved these changes, later dismissed

2022-11-29 12:04 UTC, saravanan7mani requested changes

2022-11-29 12:04 UTC, saravanan7mani commented on modules/abstract-utxo/src/recovery/backupKeyRecovery.ts
> +type WalletUnspentJSON<TNumber extends number | bigint = number> = utxolib.bitgo.WalletUnspent<TNumber> & {
It should be `type WalletUnspentJSON = utxolib.bitgo.WalletUnspent & { valueString: string; };`

2022-11-29 12:04 UTC, saravanan7mani commented on modules/abstract-utxo/src/recovery/backupKeyRecovery.ts
> +    unspents: WalletUnspent<TNumber>[] | WalletUnspentJSON[];
It should be `unspents: WalletUnspentJSON[]; `

2022-11-30 04:54 UTC, OttoAllmendinger approved these changes

2022-11-30 07:57 UTC, saravanan7mani approved these changes

2022-11-30 07:58 UTC, merged