chore(statics): add ada, doge, and matic to statics
BitGo/BitGoJS pull request #3066
Opened 2022-11-29 22:40 UTC by garrett-bitgo

Ticket: BG-62775

2022-11-29 23:30 UTC, byhow approved these changes

2022-11-29 23:32 UTC, mmcshinsky-bitgo requested changes

2022-11-29 23:32 UTC, mmcshinsky-bitgo commented on modules/statics/src/coins.ts
> +  ofc('ofcMATIC', 'Matic', 18, UnderlyingAsset.MATIC, CoinKind.CRYPTO),
Why is this uppercase?

2022-11-29 23:33 UTC, mmcshinsky-bitgo requested changes

2022-11-29 23:33 UTC, mmcshinsky-bitgo commented on modules/statics/src/coins.ts
> +  ofc('ofcMATIC', 'Matic', 18, UnderlyingAsset.MATIC, CoinKind.CRYPTO),
```suggestion
  ofc('ofcmatic', 'Matic', 18, UnderlyingAsset.MATIC, CoinKind.CRYPTO),
```

2022-11-29 23:34 UTC, mmcshinsky-bitgo requested changes

2022-11-29 23:34 UTC, mmcshinsky-bitgo commented on modules/statics/src/coins.ts
> +  tofc('ofctMATIC', 'Test Matic', 18, UnderlyingAsset.MATIC, CoinKind.CRYPTO),
```suggestion
  tofc('ofctmatic', 'Test Matic', 18, UnderlyingAsset.MATIC, CoinKind.CRYPTO),
```

2022-11-30 16:14 UTC, jeremypfeifer approved these changes

2022-11-30 16:31 UTC, merged