fix(sdk-core): fix generate wallets isCold param
BitGo/BitGoJS pull request #3101
Opened 2022-12-08 21:49 UTC by BRosentreter

## Description

Fix generateWallet which  incorrectly sets isCold as long as the userKey is present. This should only happen if the wallet type is tss - the result is hot wallet creation via the /generateWallet endpoint with Express is broken & only creates hot wallets.

## Issue Number

https://bitgoinc.atlassian.net/browse/BG-63468

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Checklist:

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] My code compiles correctly for both Node and Browser environments
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My commits follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and I have properly described any BREAKING CHANGES
- [x ] The ticket or github issue was included in the commit message as a reference
- [ x] I have made corresponding changes to the documentation and on any new/updated functions and/or methods - [jsdoc](https://jsdoc.app/)
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes

2022-12-08 22:53 UTC, bitgoAaron commented on modules/sdk-core/src/bitgo/wallet/wallets.ts
> +    const isCold = !!params.userKey && params.multisigType !== 'onchain';
Looks good, can we get a quick unit test to prevent future regressions?

2022-12-08 22:53 UTC, bitgoAaron requested changes
needs test

2022-12-08 22:55 UTC, mmcshinsky-bitgo approved these changes

2022-12-14 00:12 UTC, bitgoAaron approved these changes

2022-12-14 17:03 UTC, merged