feat(sdk-core): Add support for BitGo Link
BitGo/BitGoJS pull request #3325
Opened 2023-02-23 16:18 UTC by mcalcano-bg

Ticket: POL-64

2023-02-23 19:32 UTC, derickson-bitgo approved these changes

2023-02-23 19:32 UTC, derickson-bitgo commented on modules/bitgo/test/v2/unit/link/linkWalletNonTSS.ts
> +      stakingTransaction.should.deepEqual(transferRequest);
`stakingTransaction`

2023-02-23 19:32 UTC, derickson-bitgo commented on modules/bitgo/test/v2/fixtures/link/linkWallet.ts
> +  stakingRequest: function(transactions: StakingTransaction[]) : StakingRequest {
Is the StakingRequest needed here?

2023-02-23 22:24 UTC, mcalcano-bg commented on modules/bitgo/test/v2/fixtures/link/linkWallet.ts
> +  stakingRequest: function(transactions: StakingTransaction[]) : StakingRequest {
Fixed.

2023-02-23 22:24 UTC, mcalcano-bg commented on modules/bitgo/test/v2/unit/link/linkWalletNonTSS.ts
> +      stakingTransaction.should.deepEqual(transferRequest);
Fixed.

2023-02-24 16:24 UTC, derickson-bitgo submitted a review, later dismissed

2023-02-24 16:50 UTC, mmcshinsky-bitgo requested changes

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +    return await this.bitgo
```suggestion
    return this.bitgo
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +  async send(signedTransaction: LinkSignedTransaction): Promise<TransferRequest> {
```suggestion
 send(signedTransaction: LinkSignedTransaction): Promise<TransferRequest> {
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +   * @param signedTransaction
```suggestion
   * @param Promise<signedTransaction>
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +   * @param stakingPrebuildTransaction
```suggestion
   * @param Promise<stakingPrebuildTransaction>
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +  async buildSignAndSend(signOptions: LinkSignOptions, transfer: TransferRequest): Promise<TransferRequest> {
```suggestion
 buildSignAndSend(signOptions: LinkSignOptions, transfer: TransferRequest): Promise<TransferRequest> {
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +    return await this.build(transfer)
```suggestion
    return this.build(transfer)
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +   * @param transfer
```suggestion
   * @param Promise<transfer>
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +  private async createTransferRequest({
```suggestion
  private createTransferRequest({
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +    return await this.bitgo
```suggestion
    return this.bitgo
```

2023-02-24 16:50 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/link/linkWallet.ts
> +    return await this.bitgo
```suggestion
    return this.bitgo
```

2023-04-27 01:54 UTC, closed without merging