chore(bitgojs): Onboard April Token Batch
BitGo/BitGoJS pull request #3461
Opened 2023-04-10 09:47 UTC by grsind19

Ticket: BG-70637

2023-04-10 10:40 UTC, aarvay requested changes

2023-04-10 10:40 UTC, aarvay commented on modules/statics/src/coins.ts
> +    'ANKRETH',
```suggestion
    'Ankr Staked ETH',
```

2023-04-10 20:00 UTC, zahin-mohammad reviewed
+1 to Aarvay's review

2023-04-11 05:13 UTC, aarvay approved these changes, later dismissed

2023-04-11 07:53 UTC, aarvay approved these changes

2023-04-11 07:59 UTC, merged