Add support for ECDSA TSS with safe primes
BitGo/BitGoJS pull request #3491
Opened 2023-04-17 15:33 UTC by pranavjain97

2023-04-24 05:11 UTC, sachushaji reviewed
Build seems to be failing

2023-04-24 13:46 UTC, zahin-mohammad requested changes

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/bitgo/test/ecdh.ts
> +  it('signMessageWithDerivedEcdhKey/verifyEcdhSignature', function () {
Please make this title more descriptive

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
> +const createKeccakHash = require('keccak');
can use an import here instead

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
> +      sinon.stub(rangeProof, 'generateNTilde').resolves(deserializedEntChallenge);
```suggestion
      sandbox.stub(rangeProof, 'generateNTilde').resolves(deserializedEntChallenge);
```

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
> +      });
When you have mutliple tests like this, dont use the global sinon, use the sandbox instead.

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/sdk-api/src/bitgoAPI.ts
> +   * @param userId
add a comment her describing what happens if userId is not provided

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/sdk-api/src/bitgoAPI.ts
> +  async getECDHKeychain(ecdhKeychainPub?: string): Promise<any> {
Update the comment for this fn. It is no longer only for receiving shares. it is also for signing now.

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/bitgoBase.ts
> +  getECDHKeychain(ecdhKeychainPub?: string): Promise<any>;
can we have a better type then any here

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/enterprise/iEnterprise.ts
> +  uploadAndEnableEcdsaSigning(
enabling signing is a side effect of this fn, but what it actually does is just upload their challenge.

```suggestion
  uploadTssEcdsaChallenge(
```

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
> +    const result = await bitgo.get(bitgo.url(urlPath, 2)).query({}).result();
can this be delegated to a function on the wallet class? It's a little odd to do it here.

2023-04-24 13:46 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/ecdh.ts
> +export function signMessageWithDerivedEcdhKey(message: string, xprv: string, path: string): Buffer {
Let's add unit tests for these new functions.

2023-04-24 20:46 UTC, pranavjain97 commented on modules/bitgo/test/v2/unit/internal/tssUtils/ecdsa.ts
> +const createKeccakHash = require('keccak');
unrelated change

2023-04-25 14:56 UTC, rlutzbitgo approved these changes
Thought Zahin's comments were good, also agree that throwing on attempting to retrieve an eddsa challenge makes sense at least until we switch primes. Not blocking over it though. Nice job!

2023-04-25 15:18 UTC, zahin-mohammad approved these changes

2023-04-25 15:19 UTC, merged

2023-04-25 17:06 UTC, pranavjain97 commented
>agree that throwing on attempting to retrieve an eddsa challenge makes sense at least until we switch primes

We already have a check for ecdsa curve before retriveing a challenge on the `/challenge` api it uses, so we should be fine there.