feat(sdk-coin-btc): find & use supplementary unspents in case
BitGo/BitGoJS pull request #3532
Opened 2023-05-02 07:16 UTC by rushilbg

inscription unspent amount is not enough to cover fees

BG-72602

2023-05-02 13:31 UTC, davidkaplanbitgo requested changes

2023-05-04 13:14 UTC, davidkaplanbitgo approved these changes, later dismissed

2023-05-05 13:37 UTC, LeoKotschenreuther reviewed
Automatic comment to flush this PR from my review queue. 🚽🚽🚽
Please re-request another review from the respective team(s) when you are ready for reviews.

2023-05-05 15:21 UTC, sachushaji reviewed
Flush!!!

2023-05-08 11:46 UTC, OttoAllmendinger requested changes

2023-05-08 11:46 UTC, OttoAllmendinger commented on modules/sdk-coin-btc/src/inscriptionBuilder.ts
> +    }
could be simplified a little bit, reducing nesting

```
for (const minValue of SUPPLEMENTARY_UNSPENTS_MIN_VALUE_SATS) {
  try {
    return await this.prepareTransferWithExtraInputs(..., { minValue });
  } catch (e) {
    if (error instanceof ErrorNoLayout) {
      // try next minValue
      continue; 
    }
    throw e;
 }
}

throw new Error('Fee too high for the selected unspent with this fee rate'); // Exhausted all tries to supplement
```

2023-05-08 12:59 UTC, OttoAllmendinger approved these changes

2023-05-08 13:19 UTC, merged