fix(utxo-lib): witness utxo should not be added for non-segwit PSBT i…
BitGo/BitGoJS pull request #3542
Opened 2023-05-05 11:25 UTC by saravanan7mani

…nput

As per BIP-174, witnessUtxo should not be added for non-segwit inputs. So removing it.

Ticket: BG-76926

2023-05-05 11:36 UTC, davidkaplanbitgo requested changes
what inputs would go through `addWalletUnspentToPsbt` that dont have a witness?

2023-05-05 13:11 UTC, saravanan7mani commented
> what inputs would go through `addWalletUnspentToPsbt` that dont have a witness?

p2sh

2023-05-05 21:11 UTC, brandonblack approved these changes

2023-05-08 09:17 UTC, OttoAllmendinger approved these changes

2023-05-08 13:53 UTC, davidkaplanbitgo approved these changes

2023-05-09 05:16 UTC, merged