feat(root): implement eddsa signing with commitment
BitGo/BitGoJS pull request #3573
Opened 2023-05-17 23:47 UTC by alebusse

implemented eddsa signing with commitment   updated unit tests

BG-70695

2023-05-22 16:32 UTC, rlutzbitgo approved these changes, later dismissed

2023-05-23 17:41 UTC, pranavjain97 requested changes

2023-05-23 17:41 UTC, pranavjain97 commented on modules/sdk-core/src/account-lib/mpc/tss/eddsa/eddsa.ts
> +    }
I think it'll be better if we move the commitment to be a part of the R share. That way you don't have to do all this logic of trying to map the commitments 1:1 to the R-share and it's more intuitive.

2023-05-23 18:33 UTC, pranavjain97 requested changes
Thanks for updating it. I also remember we discussed the logic where you would make it backwards compatible based on the txrequest state, but I don't see that here. Is it being done separately?

2023-05-23 18:39 UTC, alebusse commented on modules/sdk-core/src/account-lib/mpc/tss/eddsa/types.ts
> +  commitment?: Commitment;
I will change it, i just took whats was in the first pr, but it would make it harder to extend if we need to add something later on.

2023-05-23 18:47 UTC, alebusse commented
> Thanks for updating it. I also remember we discussed the logic where you would make it backwards compatible based on the txrequest state, but I don't see that here. Is it being done separately?

Thats is in the next pr https://github.com/BitGo/BitGoJS/pull/3574, im updating it right now with the changes done here.

2023-05-23 19:27 UTC, pranavjain97 approved these changes

2023-05-23 19:33 UTC, CapnMigraine approved these changes

2023-05-23 19:44 UTC, evanzbitgo approved these changes

2023-05-23 19:47 UTC, merged