feat(utxo-lib): refactor psbt input updates out of add
BitGo/BitGoJS pull request #3608
Opened 2023-05-31 21:24 UTC by davidkaplanbitgo

BG-72538

2023-06-01 09:53 UTC, saravanan7mani requested changes

2023-06-01 09:53 UTC, saravanan7mani commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +  updateWalletUnspentForPsbt(psbt, psbt.inputCount - 1, u, rootWalletKeys, signer, cosigner);
Does PSBT object allows updating if data already exist?

2023-06-01 09:53 UTC, saravanan7mani commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +  if (inputIndex < 0 || inputIndex >= psbt.inputCount) {
`checkForInput(psbt.data.inputs, inputIndex)` can be used.

2023-06-01 15:00 UTC, OttoAllmendinger requested changes
few naming suggestions

2023-06-01 15:00 UTC, OttoAllmendinger commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +function addBaseUnspentToPsbt(psbt: UtxoPsbt, u: Unspent<bigint>): void {
```suggestion
function addUnspentToPsbt(psbt: UtxoPsbt, u: Unspent<bigint>): void {
```

2023-06-01 15:00 UTC, OttoAllmendinger commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +export function updateReplayProtectionUnspentToPsbt(
```suggestion
export function updatePsbtRedeemScript(
```

2023-06-02 14:24 UTC, davidkaplanbitgo commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +export function addReplayProtectionUnspentToPsbt(psbt: UtxoPsbt, u: Unspent<bigint>, redeemScript: Buffer): void {
Not sure if it is a good idea to change the name of this function in this PR - would have breaking changes

2023-06-02 14:25 UTC, OttoAllmendinger commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +export function addReplayProtectionUnspentToPsbt(psbt: UtxoPsbt, u: Unspent<bigint>, redeemScript: Buffer): void {
good point

2023-06-06 11:36 UTC, OttoAllmendinger requested changes

2023-06-06 11:36 UTC, OttoAllmendinger commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +  }
shouldn't you use `inputIndex` here?

2023-06-06 11:36 UTC, OttoAllmendinger commented on modules/utxo-lib/test/bitgo/psbt/Psbt.ts
> +    componentsOnEachScriptType[scriptType].forEach((inputComponent) => {
nice test

2023-06-06 14:48 UTC, OttoAllmendinger approved these changes

2023-06-06 15:01 UTC, saravanan7mani approved these changes

2023-06-06 15:04 UTC, merged