fix(sdk-core): fix createTssBitGoKeyFromOvcShares method
BitGo/BitGoJS pull request #3694
Opened 2023-06-26 18:07 UTC by alebusse

changed the method response to match with OVC expected JSON, wrapping the response in wallet: {...} and renaming the walletgpgkeys field

WP-152

2023-06-26 18:16 UTC, pranavjain97 approved these changes, later dismissed

2023-06-27 12:00 UTC, OttoAllmendinger requested changes
please submit whitespace changes separately

I thought we had a prettier set up for this?

2023-06-27 14:06 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/keychain/ovcJsonCodec.ts
> +export const BitGoToOvcJSON = t.strict(
you can create a type from this.

2023-06-27 14:06 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/keychain/keychains.ts
>      const bitgoToOvcOutput = {
you can add a type to this from the codec type.

2023-06-27 15:51 UTC, pranavjain97 approved these changes

2023-06-27 16:03 UTC, zahin-mohammad approved these changes

2023-06-27 16:58 UTC, OttoAllmendinger approved these changes

2023-06-27 17:29 UTC, merged