chore(sdk-coin-bsc): rename bsc to bnb
BitGo/BitGoJS pull request #3701
Opened 2023-06-29 19:26 UTC by kxl4126

Ticket: EA-709

2023-06-29 20:24 UTC, mmcshinsky-bitgo commented on modules/account-lib/src/index.ts
> +  tbsc: Bnb.TransactionBuilder,
```suggestion
  bnb: Bnb.TransactionBuilder,
  tbnb: Bnb.TransactionBuilder,
```

2023-06-29 20:24 UTC, mmcshinsky-bitgo requested changes
All these commits will need to be marked as breaking changes in the commit footer.

2023-06-29 22:33 UTC, mmcshinsky-bitgo commented on modules/sdk-coin-bsc/README.md
> +sdk.register('bsc', Bnb.createInstance);
```suggestion
sdk.register('bnb', Bnb.createInstance);
```

2023-06-29 23:07 UTC, islamaminBitGo commented
We want to be wary of a possible HSM change as well.

2023-06-29 23:27 UTC, mmcshinsky-bitgo commented
Has there been consideration in not touching this module until it is fully deprecated and spinning up a new bnb module?

2023-06-30 07:32 UTC, sachushaji reviewed
Think we can keep the chain name as Binance smart chain itself, Not BNB smart chain, Other than that things looks good, Adding do not merge for this untill we made associated changes in all other Microservices. Think we have a lot of places to update inorder to have this updated everywhere and also we can consider @mmcshinsky-bitgo suggestion so that this becomes non-breaking

2023-06-30 14:52 UTC, zahin-mohammad reviewed
Flushing from review Q, please re-request review once this is ready.

2023-06-30 20:47 UTC, kxl4126 commented on modules/statics/src/coins.ts
> +    'BNB Smart Chain',
Oh I think BSC is trying to distance itself from Binance exchange so they want to brand BSC (the chain) as BNB Smart Chain. That's what I read at least.

2023-06-30 20:49 UTC, kxl4126 commented on modules/statics/src/coins.ts
> +    'BNB Smart Chain',
https://cointelegraph.com/learn/a-beginners-guide-to-the-bnb-chain-the-evolution-of-the-binance-smart-chain#:~:text=BNB%20vs.&text=The%20Binance%20Chain%2C%20where%20staking,Chain%2C%20still%20abbreviated%20as%20BSC.

The Binance Chain, where staking and voting occur (BNB Chain Governance), has changed its identity to BNB Beacon Chain under the rebranded BNB Chain umbrella. The Binance Smart Chain, which supports several blockchains and is compatible with the EVM, is known simply as BNB Smart Chain, still abbreviated as BSC.

2023-06-30 20:59 UTC, kxl4126 commented
> Has there been consideration in not touching this module until it is fully deprecated and spinning up a new bnb module?

I think this is good route to take --- I'll follow up with team.

2023-07-08 21:16 UTC, closed without merging