fix(sui): support stake many
BitGo/BitGoJS pull request #3706
Opened 2023-07-05 18:30 UTC by ewangbitgo

Ticket: EA-549

2023-07-05 19:38 UTC, evanzbitgo submitted a review, later dismissed

2023-07-05 19:44 UTC, mmcshinsky-bitgo requested changes

2023-07-05 19:44 UTC, mmcshinsky-bitgo commented on modules/sdk-coin-sui/src/lib/stakingBuilder.ts
> +  stake(request: RequestAddStake[]): this {
Undocumented Breaking Change in method parameters.

2023-07-05 19:44 UTC, mmcshinsky-bitgo commented on modules/sdk-coin-sui/src/lib/utils.ts
> +  getStakeRequests(tx: StakingProgrammableTransaction): RequestAddStake[] {
Can we get documentation for this function?

2023-07-05 22:20 UTC, evanzbitgo approved these changes

2023-07-06 15:16 UTC, mmcshinsky-bitgo approved these changes

2023-07-06 15:57 UTC, merged