chore(sdk-core): add clarity to other commonKeychain util
BitGo/BitGoJS pull request #3759
Opened 2023-07-25 21:05 UTC by kxl4126

Ticket: BG-0000

2023-07-25 21:07 UTC, zahin-mohammad requested changes

2023-07-25 21:07 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
> +   * @param commonKeychain - a user uploaded commonKeychain string
Does this function throw any errors?

2023-07-25 21:07 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
> +   * @param commonKeychain - a user uploaded commonKeychain string
Can you also please add non-happy path tests?

2023-07-26 12:49 UTC, zahin-mohammad approved these changes

2023-07-26 12:49 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsa.ts
> +  static getUncompressedPublicKeyFromCommonKeychain(commonKeychain: string) {
This naming is little clearer
```suggestion
  static validateCommonKeychainPublicKey(commonKeychain: string) {
```

2023-07-26 12:58 UTC, alebusse reviewed
I dont think you need `chai`, you could use `should` in a similar way

2023-07-26 17:26 UTC, alebusse approved these changes

2023-07-26 17:30 UTC, merged