fix(abstract-cosmos): getAccountDetails fix
BitGo/BitGoJS pull request #3785
Opened 2023-08-04 14:35 UTC by DinshawKothari

Ticket: WIN-180

2023-08-04 14:39 UTC, zahin-mohammad requested changes, later dismissed

2023-08-04 14:39 UTC, zahin-mohammad commented on modules/abstract-cosmos/src/cosmosCoin.ts
> +      ['/ethermint.types.v1.EthAccount', '/injective.types.v1beta1.EthAccount'].includes(response.body.account['@type'])
Two things here:
- define these string constants somewhere
- add a test for this change

2023-08-07 03:32 UTC, mukeshsp approved these changes

2023-08-07 06:42 UTC, Phani024 approved these changes

2023-08-07 06:57 UTC, merged