feat(utxo-lib): build transaction without nonWitnessUtxo when specified
BitGo/BitGoJS pull request #4050
Opened 2023-11-08 21:34 UTC by davidkaplanbitgo

TICKET: BTC-606

In the instance that we want to doing a bulk sweep, for network and client performance reasons we are substituting the nonWitnessUtxo for p2sh and p2shP2pk inputs with a witnessUtxo. We need the witnessUtxo so that we can half sign the transaction locally with the user key. When we send the half signed to BitGo, the PSBT will be properly populated such that the non-segwit inputs have the nonWitnessUtxo. This means when we send it to BitGo we should remove the witnessUtxo so that it just has the partialSig and redeemScript.

2023-11-08 21:44 UTC, lcovar submitted a review, later dismissed

2023-11-09 06:04 UTC, rushilbg approved these changes, later dismissed

2023-11-09 07:10 UTC, saravanan7mani requested changes

2023-11-09 07:10 UTC, saravanan7mani commented on modules/utxo-lib/src/bitgo/wallet/Unspent.ts
> +    psbt.updateInput(inputIndex, { witnessUtxo: { script, value } });
```
if (customParams?.skipNonWitnessUtxo || (isZcash && !input.witnessUtxo)) {
    const { script, value } = toPrevOutput(u, psbt.network);
    psbt.updateInput(inputIndex, { witnessUtxo: { script, value } });
}
```

2023-11-09 12:37 UTC, saravanan7mani approved these changes

2023-11-09 13:31 UTC, merged