feat(statics): add Litentry (LIT) and Ampleforth (AMPL) as tokens
BitGo/BitGoJS pull request #4068
Opened 2023-11-14 17:45 UTC by evalenti-simtlix

Add Litentry (LIT) and Ampleforth (AMPL) as tokens

EA-2217

2023-11-14 18:25 UTC, alebusse approved these changes, later dismissed

2023-11-15 16:34 UTC, mmcshinsky-bitgo requested changes

2023-11-15 16:34 UTC, mmcshinsky-bitgo commented on modules/statics/src/coins.ts
> +    'Litenry',
```suggestion
    'Litentry',
```

2023-11-15 20:40 UTC, kxl4126 approved these changes

2023-11-15 20:54 UTC, mmcshinsky-bitgo approved these changes

2023-11-16 14:42 UTC, merged