feat: allow replacement transaction verification after prebuild
BitGo/BitGoJS pull request #4218
Opened 2024-01-24 13:55 UTC by rushilbg

[feat: allow replacement transaction verification after prebuild](https://github.com/BitGo/BitGoJS/commit/5ba8203d595f2650e6bf08ef4ee9527bfdcf79ec) 

The verification will happen based on the recipients of the original
transaction that is being replaced instead of the recipients of the
replacement transaction API request, which is empty always.

[BTC-820](https://bitgoinc.atlassian.net/browse/BTC-820)

2024-01-24 14:01 UTC, OttoAllmendinger requested changes
nit

2024-01-24 14:01 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> +    if (txParams.rbfTxIds) {
```suggestion
    if (txParams.rbfTxIds) {
      assert(txParams.rbfTxIds.length === 1);
```

2024-01-24 14:05 UTC, OttoAllmendinger reviewed
maybe I am missing something

2024-01-24 14:05 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> +  rbfTxIds?: string;
```suggestion
  rbfTxIds?: string[];
```
?

2024-01-24 14:17 UTC, OttoAllmendinger submitted a review, later dismissed

2024-01-24 17:01 UTC, OttoAllmendinger approved these changes

2024-01-25 07:51 UTC, ayush-9 approved these changes

2024-01-25 07:52 UTC, merged