Wp 1401 implement eddsa multisig derivation
BitGo/BitGoJS pull request #4276
Opened 2024-02-12 16:38 UTC by alebusse

2024-02-13 11:21 UTC, OttoAllmendinger reviewed
flush draft

2024-02-15 19:28 UTC, mmcshinsky-bitgo commented
@alebusse BREAKING CHANGE needs to be in the commit footer to be recognized correctly

2024-02-15 19:31 UTC, mmcshinsky-bitgo requested changes
@alebusse BREAKING CHANGE needs to be in the commit footer to be recognized correctly

2024-02-15 19:31 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/account-lib/index.ts
> +// Deprecated
redundant comment

2024-02-15 19:31 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/account-lib/util/eddsaKeyDeriver.ts
> +export class EddsaKeyDeriver {
Needs JS Docs for methods

2024-02-15 19:32 UTC, mmcshinsky-bitgo commented
@alebusse There are modules that are only test that aren't part of the breaking change for the module itself. This PR needs to be broken up into multiple commits so that the breaking change doesn't wrongfully bump incorrect packages.

2024-02-15 19:36 UTC, alebusse commented
> @alebusse BREAKING CHANGE needs to be in the commit footer to be recognized correctly

good to know, i didnt manually created the commmit msg, commitizen cli does it for me, i follow the steps.

2024-02-15 19:37 UTC, alebusse commented
> @alebusse There are modules that are only test that aren't part of the breaking change for the module itself. This PR needs to be broken up into multiple commits so that the breaking change doesn't wrongfully bump incorrect packages.

Make sense, this is not actually a PR to merge or review, is just a POC for Islam to review and work on the missing part. But i think we wont even be doing this now, im testing something else

2024-02-19 22:43 UTC, closed without merging