docs: add example to accelerate transaction using RBF in cold wallets
BitGo/BitGoJS pull request #4285
Opened 2024-02-15 11:08 UTC by rushilbg

docs: add example to accelerate transaction using RBF in cold wallets

BTC-898

2024-02-15 15:10 UTC, mullapudipruthvik approved these changes

2024-02-15 19:18 UTC, mmcshinsky-bitgo requested changes
nit: focus commits to `feat(sdk-core)`

2024-02-15 19:18 UTC, mmcshinsky-bitgo commented on examples/ts/btc/rbf/cold/original-tx-submit.ts
> +const bitgo = new BitGo({ env: rbfConfig.env as EnvironmentName });
Use BitGoAPI examples over new BitGo

2024-02-15 19:18 UTC, mmcshinsky-bitgo commented on examples/ts/btc/rbf/cold/original-tx.ts
> +const bitgo = new BitGo({ env: rbfConfig.env as EnvironmentName });
Same change here

2024-02-15 19:18 UTC, mmcshinsky-bitgo commented on examples/ts/btc/rbf/cold/replacement-tx-submit.ts
> +const bitgo = new BitGo({ env: rbfConfig.env as EnvironmentName });
Same change here

2024-02-15 19:18 UTC, mmcshinsky-bitgo commented on examples/ts/btc/rbf/cold/replacement-tx.ts
> +const bitgo = new BitGo({ env: rbfConfig.env as EnvironmentName });
Same change here

2024-02-15 19:18 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/wallet/wallet.ts
> +    // FIXME: Prefer to use the below assertion for more robustness.
Can we add a ticket to track this?

2024-02-15 19:18 UTC, mmcshinsky-bitgo commented on modules/sdk-core/src/bitgo/wallet/wallet.ts
> +  async enhanceColdPrebuildTransaction(tx) {
Missing JSdocs as well as type annotation for the parameter and return value.

2024-03-08 17:44 UTC, zahin-mohammad reviewed
Looks like there is already a bit of un-addressed feedback. Feel free to re-request a review when it is ready for review again.

2024-05-03 01:48 UTC, closed without merging