chore: bump crypto-js dependency
BitGo/BitGoJS pull request #4334
Opened 2024-03-05 21:27 UTC by angshal

TICKET: CE-3554

## Description

crypto-js version is causing a dependabot alert for bitgo-ui: https://github.com/BitGo/bitgo-ui/security/dependabot/36. 
This PR updates the `@hashgraph/cryptography` and `@hashgraph/sdk` packages which subsequently updates the `crypto-js` dependency

2024-03-06 11:50 UTC, rushilbg approved these changes, later dismissed

2024-03-06 12:25 UTC, ajays97 submitted a review, later dismissed

2024-03-08 17:32 UTC, zahin-mohammad approved these changes, later dismissed

2024-04-10 17:16 UTC, andrew-scott-fischer commented
resolved merge conflicts

2024-04-11 18:59 UTC, zahin-mohammad requested changes
PR not ready for review. Please tag the @BitGo/wallet-platform  once this is ready again

2024-04-11 21:00 UTC, lcovar reviewed
flushing queue

2024-04-25 16:53 UTC, closed without merging