docs(root): remove ndoe 16
BitGo/BitGoJS pull request #4371
Opened 2024-03-26 17:42 UTC by zahin-mohammad

This was missed as part of https://github.com/BitGo/BitGoJS/pull/4119
TICKET: WP-1100

2024-03-26 17:45 UTC, gianchandania submitted a review, later dismissed

2024-03-26 18:12 UTC, andrew-scott-fischer requested changes, later dismissed
should be `<21`

2024-03-26 18:12 UTC, andrew-scott-fischer commented on DEVELOPERS.md
> +- node version >=18 and <20
```suggestion
- node version >=18 and <21
```

2024-03-26 18:12 UTC, andrew-scott-fischer commented on DEVELOPERS.md
> +- node version >=18 and <20
we support `20`, but not `21`

2024-03-26 18:15 UTC, andrew-scott-fischer reviewed
I pushed the fix.

2024-03-27 04:57 UTC, aarvay approved these changes

2024-03-27 13:00 UTC, merged