chore(root): add script to fetch trx:usdt balance for addresses
BitGo/BitGoJS pull request #4374
Opened 2024-03-27 10:42 UTC by adarsh312

Ticket: WIN-2550

2024-03-28 04:38 UTC, Vijay-Jagannathan submitted a review, later dismissed

2024-03-28 09:56 UTC, ajays97 submitted a review, later dismissed
LGTM, but pipeline is failing in unit tests due to Dependency Audit vulnerability issues.

2024-04-02 00:38 UTC, zahin-mohammad requested changes

2024-04-02 00:38 UTC, zahin-mohammad commented on examples/ts/trx/fetch-addresses-not-eligible-for-usdt-consolidation.ts
> +  const command = "bga address updateNeedsConsolidationFlag  --needsConsolidation false --addresses ";
`bga` is not public facing tooling. Please remove this from this repo.

2024-04-05 04:49 UTC, Vijay-Jagannathan approved these changes

2024-04-05 15:17 UTC, zahin-mohammad approved these changes

2024-04-10 06:11 UTC, merged