feat(ada): support passing unspents as build param
BitGo/BitGoJS pull request #4570
Opened 2024-05-28 06:09 UTC by hitansh-bitgo

Ticket: WIN-1832

2024-06-02 22:16 UTC, margueriteblair requested changes
Please add context for why we're making these changes? Trying to understand why the unspents would need to be passed into the intent; I feel like that doesn't make sense. Also you need tests.

2024-06-03 14:13 UTC, zahin-mohammad requested changes

2024-06-03 14:13 UTC, zahin-mohammad commented on modules/sdk-core/src/bitgo/utils/mpcUtils.ts
> +    }
Agree with @margueriteblair , why is the user not supplying intents in the intent directly?

2024-06-18 13:16 UTC, closed without merging

2024-07-04 17:06 UTC, hitansh-bitgo commented
@zahin-mohammad @margueriteblair I think I might still need this change after all. To add some context, we recently added a change to let a user specify in the intent which unspents to use for txn building for Ada https://github.com/BitGo/common-interface/pull/54. Now this works fine when using `v2.wallet.txrequest.create`, but we also need to support passing unspents in sendMany calls, and for that I'll need this change,right? Or is there a better way to go about this?