feat: enable p2trMusig2 for testnet cold wallets
BitGo/BitGoJS pull request #4606
Opened 2024-06-06 16:25 UTC by ericli-bitgo

TICKET: BTC-1229

2024-06-07 11:33 UTC, rushilbg commented on modules/sdk-core/src/bitgo/utils/abstractUtxoCoinUtil.ts
>    // Only return true for p2trMusig2 if the wallet type is hot
This comment would need to be updated as well.

2024-06-21 06:21 UTC, OttoAllmendinger requested changes
this is getting hard to follow

can you add a function

```
function isEnabledAddressType(network: utxolib.Network, walletType: string, scriptType: ScriptType2Of3): boolean
```

2024-06-21 13:40 UTC, OttoAllmendinger requested changes

2024-06-21 13:40 UTC, OttoAllmendinger commented on modules/sdk-core/src/bitgo/utils/abstractUtxoCoinUtil.ts
> +    return true;
```suggestion
    return utxolib.isSupportedScriptType(network, scriptType);
```

2024-06-21 13:40 UTC, OttoAllmendinger commented on modules/sdk-core/src/bitgo/utils/abstractUtxoCoinUtil.ts
> +}
```suggestion
function isEnabledAddressType(network: utxolib.Network, walletType: WalletType, scriptType: ScriptType2Of3): boolean {
  if (!utxolib.isSupportedScriptType(network, scriptType)) {
    return false;
  }
  if (scriptType === 'p2trMusig2') {
    return walletType === 'hot' || (walletType === 'cold' && utxolib.isTestnet(network));
  }
  return true;
}
```

2024-06-21 14:12 UTC, OttoAllmendinger approved these changes, later dismissed

2024-06-21 14:30 UTC, OttoAllmendinger requested changes

2024-06-21 14:30 UTC, OttoAllmendinger commented on modules/sdk-core/src/bitgo/utils/abstractUtxoCoinUtil.ts
> +  // Only return true for p2trMusig2 if the wallet type is hot or cold on testnet
```suggestion
```

2024-06-22 18:45 UTC, OttoAllmendinger approved these changes

2024-06-24 18:02 UTC, merged