feat: add wasm-miniscript module
BitGo/BitGoJS pull request #4705
Opened 2024-07-08 14:26 UTC by OttoAllmendinger

Wrap the `rust-miniscript` library in a WebAssembly module.

This is just a rough skeleton making sure the CI pipeline works.

Issue: BTC-1317

2024-07-09 09:26 UTC, saravanan7mani submitted a review, later dismissed

2024-07-10 16:54 UTC, zahin-mohammad requested changes
Can you please update the relevant readme's to let devs know they need to install rust.

From my understanding looks like we are directly committing the source rust code, and generating the wasm at build time?

2024-07-10 16:58 UTC, zahin-mohammad commented on modules/wasm-miniscript/test/descriptorFixtures.ts
> +//This file is generated automatically. Do not edit it!
Any notice we should add for this code snippet? Do we need to make this specific module under the MIT license?

2024-07-10 18:45 UTC, OttoAllmendinger commented on modules/wasm-miniscript/test/descriptorFixtures.ts
> +//This file is generated automatically. Do not edit it!
good idea

2024-07-10 18:55 UTC, OttoAllmendinger commented
moving to separate repo

2024-07-10 18:55 UTC, closed without merging