fix(sdk-core): support backup party id in mpcv2 signing utils
BitGo/BitGoJS pull request #4765
Opened 2024-07-25 15:46 UTC by islamaminBitGo

TICKET: HSM-442

2024-07-25 16:19 UTC, mohammadalfaiyazbitgo reviewed
any unit tests you can add for this?

2024-07-25 16:20 UTC, mohammadalfaiyazbitgo commented on modules/sdk-core/src/bitgo/tss/ecdsa/ecdsaMPCv2.ts
> +  partyId: 0 | 1 = 0
any reason you're using `0 | 1` instead of `boolean` ?

2024-07-25 16:33 UTC, islamaminBitGo commented
> any unit tests you can add for this?

there is no value of any additional tests in my opinion, the user signing is tested so adding a backup signing test would be a clone of that

2024-07-25 20:50 UTC, pranavjain97 requested changes, later dismissed
Changes look good. Can you add a test with the backup id case here `tssUtils/ecdsaMPCv2/signTxRequest.ts`?

2024-07-25 20:51 UTC, pranavjain97 commented
> > any unit tests you can add for this?
> 
> there is no value of any additional tests in my opinion, the user signing is tested so adding a backup signing test would be a clone of that

It's more so that nobody removes that logic from this code if there is test for it

2024-07-25 20:56 UTC, alebusse commented
do we want to change the top method signRequestBase too https://github.com/BitGo/BitGoJS/blob/a481acddd572873aa9d3303f97832dbe88289de8/modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsaMPCv2.ts#L698?

2024-07-25 21:42 UTC, islamaminBitGo commented
> do we want to change the top method signRequestBase too
> 
> https://github.com/BitGo/BitGoJS/blob/a481acddd572873aa9d3303f97832dbe88289de8/modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsaMPCv2.ts#L698
> 
> ?

i feel this might be out of scope for this PR since this is meant only for the utils that other apps are using rather than the hot wallet regular flow itself. Nevertheless, yes, I think we can do this but in a follow up ticket + PR

2024-07-25 21:54 UTC, islamaminBitGo commented
actuall

> > do we want to change the top method signRequestBase too
> > https://github.com/BitGo/BitGoJS/blob/a481acddd572873aa9d3303f97832dbe88289de8/modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsaMPCv2.ts#L698
> > 
> > ?
> 
> i feel this might be out of scope for this PR since this is meant only for the utils that other apps could be using (such as WRW) rather than the hot wallet regular flow itself. Nevertheless, yes, I think we can do this but in a follow up ticket + PR

actually on second thought, it's not a big change so i think it's ok to include it in this ticket. will apply this change as well

2024-07-25 22:57 UTC, islamaminBitGo commented
> Changes look good. Can you add a test with the backup id case here `tssUtils/ecdsaMPCv2/signTxRequest.ts`?

done

2024-07-25 22:57 UTC, islamaminBitGo commented
> do we want to change the top method signRequestBase too
> 
> https://github.com/BitGo/BitGoJS/blob/a481acddd572873aa9d3303f97832dbe88289de8/modules/sdk-core/src/bitgo/utils/tss/ecdsa/ecdsaMPCv2.ts#L698
> 
> ?

done

2024-07-26 14:48 UTC, mohammadalfaiyazbitgo approved these changes

2024-07-26 16:53 UTC, merged