feat(abstract-utxo): add address creation for descriptor wallets
BitGo/BitGoJS pull request #4849
Opened 2024-08-23 16:22 UTC by ericli-bitgo

2024-08-26 07:35 UTC, OttoAllmendinger requested changes

2024-08-26 07:35 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> +  descriptor: NamedDescriptor;
```suggestion
  descriptors: NamedDescriptor[];
```

2024-08-26 10:31 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> +
this should be a static method

2024-08-26 10:32 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> +        descriptor: params.coinSpecific.descriptor,
we only submit the name of the descriptor (the full descriptor itself is defined on the wallet)

2024-08-27 16:11 UTC, pranavjain97 reviewed
WP changes look fine. Please request re-review when Otto's changes are addressed

2024-09-03 08:27 UTC, OttoAllmendinger approved these changes

2024-09-03 08:27 UTC, merged