feat(sdk-api): authenticate with passkey
BitGo/BitGoJS pull request #4933
Opened 2024-09-24 15:37 UTC by alvin-dai-bitgo

Ticket: WP-2592

Add a new method `authenticateWithPasskey`

2024-09-24 19:22 UTC, pranavjain97 requested changes

2024-09-24 19:22 UTC, pranavjain97 commented on modules/sdk-api/src/bitgoAPI.ts
> +    if (!_.isObject(params.response)) {
dont think it needs to be nested under response

2024-09-24 19:22 UTC, pranavjain97 commented on modules/sdk-api/src/bitgoAPI.ts
> +    }
what is this for? the current "response" is the replacement of the otp data

2024-09-27 15:17 UTC, pranavjain97 submitted a review, later dismissed

2024-09-27 18:38 UTC, pranavjain97 commented on modules/sdk-api/src/bitgoAPI.ts
> +    }
We'll actually extract the username from the webauthn response's userHandle in a follow-up. That way - UI can send data as it.

2024-09-27 19:10 UTC, alebusse approved these changes

2024-09-27 19:32 UTC, merged