chore(avaxc) : wrw support for evm ccr
BitGo/BitGoJS pull request #4944
Opened 2024-09-25 11:43 UTC by nrjsuthar

chore(avaxc) : wrw support for evm ccr 

TICKET: COIN-1708

2024-09-25 15:34 UTC, kamleshmugdiya commented
tests are failing

2024-09-25 16:03 UTC, kamleshmugdiya requested changes
this defeats the purpose of inheritance and code reusability.

2024-09-25 16:03 UTC, kamleshmugdiya commented on modules/sdk-coin-avaxc/src/EthLikeAvaxc.ts
> +  }
same

2024-09-25 16:45 UTC, nrjsuthar commented
@kamleshmugdiya 
This PR https://github.com/BitGo/BitGoJS/pull/4925 had the change you mentioned, where the relationship exists. The changes in the current PR were because of the Gas and Limit, wherein all the parent methods are copied. The ideal change would be to extend avaxc class with abstractEthLikeNewCoin (mentioned PR), but removed as no one was sure of the change.

2024-09-25 16:47 UTC, nrjsuthar commented
Also, the gas price and limit from the explorer were not required here for the half sign.

2024-09-25 16:48 UTC, nrjsuthar commented on modules/sdk-coin-avaxc/src/EthLikeAvaxc.ts
> +  async recoveryBlockchainExplorerQuery(query: Record<string, any>): Promise<any> {
ok

2024-09-25 17:11 UTC, kamleshmugdiya commented
> @kamleshmugdiya This PR #4925 had the change you mentioned, where the relationship exists. The changes in the current PR were because of the Gas and Limit, wherein all the parent methods are copied. The ideal change would be to extend avaxc class with abstractEthLikeNewCoin (mentioned PR), but removed as no one was sure of the change.

I don't understand this, if the function has the same impl in AbstractEthLikeNewCoins, what is the need to override with the same code in the new class?

2024-09-25 17:17 UTC, nrjsuthar commented
> > @kamleshmugdiya This PR #4925 had the change you mentioned, where the relationship exists. The changes in the current PR were because of the Gas and Limit, wherein all the parent methods are copied. The ideal change would be to extend avaxc class with abstractEthLikeNewCoin (mentioned PR), but removed as no one was sure of the change.
> 
> I don't understand this, if the function has the same impl in AbstractEthLikeNewCoins, what is the need to override with the same code in the new class?

This was based on testing, for each of the issues, the method has been copied. 

Example:

A -> B -> C is the method flow and A has to be changed, now i we need to change the method A over here, we will need to override all its parents, the sub method will not be able to be called.

2024-09-25 18:27 UTC, kamleshmugdiya commented
> > > @kamleshmugdiya This PR #4925 had the change you mentioned, where the relationship exists. The changes in the current PR were because of the Gas and Limit, wherein all the parent methods are copied. The ideal change would be to extend avaxc class with abstractEthLikeNewCoin (mentioned PR), but removed as no one was sure of the change.
> > 
> > 
> > I don't understand this, if the function has the same impl in AbstractEthLikeNewCoins, what is the need to override with the same code in the new class?
> 
> This was based on testing, for each of the issues, the method has been copied.
> 
> Example:
> 
> A -> B -> C is the method flow and A has to be changed, now i we need to change the method A over here, we will need to override all its parents, the sub method will not be able to be called.

what testing?
and the methods that I pointed out, do they have any difference in implementation vs the AbstractEthLikeNewCoins?
they all looked the same to me.

2024-09-26 05:58 UTC, kamleshmugdiya commented on modules/sdk-coin-avaxc/src/avaxc.ts
> +  private ethLikeAvaxc: any;
1. Why is composition relationship required?
2. can you name this better EthLikeAvaxc?
just by name, I am not able to understand what is the diff between EthLikeAvaxc and AvaxC.

2024-09-26 07:58 UTC, kamleshmugdiya commented
pipeline failing again

2024-09-26 17:40 UTC, closed without merging