chore(sdk-api): enable esModuleInterop
BitGo/BitGoJS pull request #4978
Opened 2024-10-02 12:38 UTC by OttoAllmendinger

Requires some changes to the imports in the codebase to use the default import
syntax.

Issue: BTC-1351

2024-10-02 21:00 UTC, davidkaplanbitgo approved these changes

2024-10-02 21:06 UTC, lzjluzijie approved these changes

2024-10-03 14:04 UTC, zahin-mohammad requested changes
The changes look good to me but, 
- lacking context on why we need this change 
- the linked ticket seems irrelevant to this change (maybe it is, its just not obvious to me)

2024-10-07 08:44 UTC, OttoAllmendinger commented
@zahin-mohammad fair point, opened #4991 with fixed issue number and improved description

2024-10-07 08:44 UTC, closed without merging