BTC-1553: fix isValidAddress by using toCanonicalFormat
BitGo/BitGoJS pull request #5019
Opened 2024-10-11 16:34 UTC by kcheng-bitgo

TICKET: BTC-1553
Previously, `isValidAddress` verified the address by converting it to script and back. However, the previous implementation converts the script back to the legacy address and compares it against the original address. Thus, if the original was cashaddr format, it would fail. `toCanonicalFormat` does this conversion as well, and if it succeeds, that means the address was valid.

2024-10-11 16:35 UTC, davidkaplanbitgo approved these changes, later dismissed

2024-10-11 20:29 UTC, davidkaplanbitgo submitted a review, later dismissed

2024-10-12 10:55 UTC, OttoAllmendinger requested changes
the commit title / PR title should state what it does: with your change we return `true`

2024-10-12 10:55 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> -    const formats = param && param.anyFormat ? undefined : ['default' as const];
So previously the `anyFormat` flag controlled this behavior. What you want to do here is make `anyFormat = true` the default.

2024-10-12 10:57 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> -      return address === utxolib.address.fromOutputScript(script, this.network);
you can just remove this line - `toOutputScriptsTryFormats` will fail if it cannot parse the address with any of the formats

2024-10-15 16:14 UTC, davidkaplanbitgo submitted a review, later dismissed

2024-10-15 23:56 UTC, pengyuc-bitgo submitted a review, later dismissed

2024-10-16 13:18 UTC, OttoAllmendinger requested changes
consider this implementation

```
// By default, allow all address formats.
// At the time of writing, the only additional address format is bch cashaddr.
const anyFormat = params.anyFormat ?? true;
try  {
  // Find out if the address is valid for any format. Tries all supported formats by default.
  // Throws if address cannot be decoded with any format.
  const [format, script] = utxolib.addressFormat.toOutputScriptAndFormat(address, network);
  // unless anyFormat is set, only 'default' is allowed.
  if (!anyFormat && format !== 'default') {
    return false;
  }
  // make sure that address is in normal representation for given format.
  return address === utxolib.addressFormat.fromOutputScriptWithFormat(script, format, network);
} catch (e) {
  return false
}
```

2024-10-16 13:18 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> +      // To make sure that we are preserving `fromOutputScript(script, network) === address`, we need to do the
```suggestion
      // To make sure that we are preserving `fromOutputScriptWithFormat(script, format, network) === address`, we need to do the
```

2024-10-16 13:18 UTC, OttoAllmendinger commented on modules/abstract-utxo/src/abstractUtxoCoin.ts
> +      return genAddresses.includes(address);
```
const [format, script] = utxolib.addressFormat.toOutputScriptAndFormat(address, network);
if (!anyFormat && format !== 'default') {
  return false;
}
return address === utxolib.addressFormat.fromOutputScriptWithFormat(script, format, network);
```

2024-10-18 12:15 UTC, OttoAllmendinger approved these changes

2024-10-18 12:19 UTC, merged