BTC 1450.bump typescript
BitGo/BitGoJS pull request #5189
Opened 2024-11-29 11:36 UTC by OttoAllmendinger

- **feat: add @types/keccak to packages that use it**
  This prepares for the Typescript 5.7 upgrade
  
  Issue: BTC-1450
  

- **fix: use better string conversion for message signing**
  It appears that `v instanceof Buffer` is not a reliable type guard in Typescript
  5.
  
  The new type guard is equivalent.
  
  Issue: BTC-1450
  

- **fix: type errors in old code**
  They are correctly detected with Typescript 5
  
  Issue: BTC-1450
  

- **fix: remove invalid types from tsconfig.json**
  These do not work any longer with Typescript 5.
  
  Issue: BTC-1450
  

- **feat: update typescript to 5.7.2**
  Hopefully this improves performance with the language server
  
  Issue: BTC-1450

2024-11-29 14:47 UTC, saravanan7mani approved these changes, later dismissed

2024-11-29 21:35 UTC, alebusse requested changes

2024-11-29 21:35 UTC, alebusse commented on modules/account-lib/package.json
> +    "@types/keccak": "^3.0.5",
```suggestion
```

2024-11-29 21:36 UTC, alebusse requested changes

2024-11-29 21:36 UTC, alebusse commented on modules/account-lib/package.json
> +    "@types/keccak": "^3.0.5",
```suggestion
    "@types/keccak": "^3.0.5",
    "keccak": "3.0.3",
```

2024-12-01 17:17 UTC, zahin-mohammad approved these changes

2024-12-02 11:07 UTC, alebusse approved these changes

2024-12-03 16:20 UTC, noel-bitgo approved these changes

2024-12-03 16:31 UTC, ewangbitgo approved these changes

2024-12-03 16:35 UTC, bitgoAaron approved these changes

2024-12-03 16:46 UTC, lcovar approved these changes

2024-12-03 16:46 UTC, davidkaplanbitgo approved these changes

2024-12-03 16:47 UTC, merged