feat(sdk): added eip1559 property to statics
BitGo/BitGoJS pull request #5300
Opened 2024-12-19 16:40 UTC by varun-bitgo

TICKET: WP-1219

2024-12-19 23:35 UTC, margueriteblair commented on modules/statics/test/unit/coins.ts
> +  const eip1559Coins = [
Should also be added for `eth` and `hteth` and mainnet `avaxc` too

2024-12-20 14:12 UTC, margueriteblair commented on modules/statics/test/unit/coins.ts
> +    'tavaxc',
nit: can we reorder these so `avaxc` and `tavaxc` are next to each other? prefer all the mainnet coins to be next to their testnet coins

2024-12-20 15:30 UTC, margueriteblair approved these changes, later dismissed
lgtm

2024-12-26 13:05 UTC, margueriteblair submitted a review, later dismissed

2024-12-27 18:47 UTC, bitgoAaron approved these changes, later dismissed

2024-12-31 17:17 UTC, zahin-mohammad submitted a review, later dismissed

2024-12-31 17:33 UTC, zahin-mohammad approved these changes

2024-12-31 17:33 UTC, zahin-mohammad requested changes
Looks like a bad merge conflcit.... please fix

2024-12-31 17:55 UTC, zahin-mohammad approved these changes

2024-12-31 18:24 UTC, merged