refactor(statics): move out ERC20 tokens to dedicated file from coins.ts
BitGo/BitGoJS pull request #5306
Opened 2024-12-23 09:58 UTC by rv-bitgo

TICKET: WIN-4074

2024-12-23 12:38 UTC, ajays97 requested changes

2024-12-23 12:38 UTC, ajays97 commented on modules/statics/src/coins/erc20Coins.ts
> +import { MATIC_FEATURES, WETH_FEATURES, ETH_FEATURES } from './coins';
Isn't it supposed to be 
```suggestion
import { MATIC_FEATURES, WETH_FEATURES, ETH_FEATURES } from '../coins';
```

2024-12-23 16:54 UTC, alebusse requested changes
please squash the commits

2025-01-15 10:30 UTC, FloBitGo requested changes
This seems to be stale. Either rebase and get it ready for review again or close it.

2025-01-26 02:00 UTC, closed without merging