Update BLS initialization
BitGo/BitGoJS pull request #943
Opened 2020-11-12 22:59 UTC by wesgraham

Updates BLS initialization so client does not need to worry about dependency
Ticket: BG-26379

2020-11-12 23:00 UTC, marktoda reviewed
Yay nice. Want to run by @tylerlevine though - Tyler, this library requires this weird async initializer function to be run globally before the lib can be used. Is this the best way to handle this?

2020-11-12 23:10 UTC, tylerlevine commented
> Yay nice. Want to run by @tylerlevine though - Tyler, this library requires this weird async initializer function to be run globally before the lib can be used. Is this the best way to handle this?

The current implementation is going to kick off a race condition which could cause usage of the library before it's initialized.

Where are we going to use this? Can we lazy initialize before use? (eg, generating a key)

2020-11-12 23:55 UTC, wesgraham commented
@tylerlevine dumb question here but how would lazy initialization look? Can't stick the initialization into the constructor, and am trying to avoid i) creating the object then ii) calling `initialization()` separately

2020-11-14 01:06 UTC, tylerlevine commented
> @tylerlevine dumb question here but how would lazy initialization look? Can't stick the initialization into the constructor, and am trying to avoid i) creating the object then ii) calling `initialization()` separately

What do the calls to get to here look like? It might be the best you can do is to kick off the init in a `setImmediate` callback and then set a boolean once it's resolved, and then check to make sure the boolean is set before using the lib (or throwing if it's not set). At least you avoid weird race conditions this way.

Even better would be to find the closest async context which would use the library, and initialize it there before use. Unfortunately it doesn't look like account-lib is designed to do any async work on initialization, so callers might need to do this before using certain functions in account-lib.

2020-11-16 20:47 UTC, marktoda requested changes
I don't think this will work. The `BaseKeyPair` interface doesn't define those functions as async, so callers won't know to `await` them and they will end up with race conditions where sometimes their keypair will not be initialized by the time they try to use it. 

I think instead you should use tyler's `setImmediate` idea and throw if uninitialized when you need it

2020-11-17 18:04 UTC, wesgraham commented
@tylerlevine Was this the approach as intended? Still not certain how to get around the failing browser test (no module declaration recognized)

2020-11-19 05:39 UTC, marktoda requested changes

2020-11-19 05:39 UTC, marktoda commented on modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
> +    if (this.isValidBLSPrv(prv) && initialized) {
Why do you need this here if it is in the constructor?

2020-11-19 05:39 UTC, marktoda commented on modules/account-lib/src/coin/baseCoin/blsKeyPair.ts
> +    if (initialized) {
ditto

2020-11-19 18:34 UTC, marktoda approved these changes
LGTM

2020-11-19 19:13 UTC, merged