WIP: Add cspr and tcspr to core module
BitGo/BitGoJS pull request #980
Opened 2020-12-30 18:07 UTC by hgonzalez-simtlix

Jira card: https://simtlix.atlassian.net/browse/BGA-1165

2020-12-30 18:48 UTC, rliberal-simtlix requested changes

2020-12-30 18:48 UTC, rliberal-simtlix commented on modules/core/src/v2/coins/tcspr.ts
> +    return 'teth';
Change this for tcspr

2020-12-30 18:48 UTC, rliberal-simtlix commented on modules/core/src/v2/coins/tcspr.ts
> +    return 'Testnet Ethereum';
Tesnet Casper

2020-12-30 20:34 UTC, FabianSimtlix requested changes

2020-12-30 20:34 UTC, FabianSimtlix commented on modules/core/src/v2/coins/cspr.ts
> +        }
Why is the parameter optional if we are going to throw an exception when it's missing?

2020-12-30 20:34 UTC, FabianSimtlix commented on modules/core/src/v2/coins/cspr.ts
> +    new CsprAccountLib.KeyPair();
Indentation. It's not clear that this one correspondes with previous assignment

2020-12-30 20:34 UTC, FabianSimtlix commented on modules/core/src/v2/coins/tcspr.ts
> +}
This values should be taken from statics

2021-01-04 16:35 UTC, rliberal-simtlix commented on modules/core/test/v2/unit/coins/cspr.ts
> +  it('should return cspr', function () {
should return tcspr?

2021-01-04 18:47 UTC, rliberal-simtlix approved these changes

2021-01-05 19:22 UTC, tylerlevine submitted a review, later dismissed
lgtm, just one nit on the white space but it's not a blocker.

2021-01-05 19:22 UTC, tylerlevine commented on modules/core/src/v2/coins/cspr.ts
> +      super(bitgo);
It's a bit odd to alternate between 4 and 2 space indent. Not a blocker though. You can add the following comment at the top of the file to have prettier auto-format any changes so you don't need to think about this:
```
/*
 * @prettier
 */
```

2021-01-05 19:23 UTC, rliberal-simtlix approved these changes

2021-01-06 13:15 UTC, CapnMigraine submitted a review, later dismissed
LGTM. Please squash your commits.

2021-01-07 16:11 UTC, CapnMigraine submitted a review, later dismissed
lgtm

2021-01-08 02:30 UTC, tylerlevine approved these changes

2021-01-08 02:30 UTC, tylerlevine commented on modules/core/src/v2/coins/index.ts
> +export { Cspr } from './cspr';
Please maintain alphabetic ordering

2021-01-08 13:24 UTC, CapnMigraine approved these changes

2021-01-08 13:24 UTC, merged